### ISSUE TITLE
Crash while closing DataTimeLapse test

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-android-demo#1002]
Crash after closing  Data time lapse in dds section : 

ran against maps-sdk snapshot: 7.3.0-20190327.150253-67

![image](https://user-images.githubusercontent.com/32496536/55104923-b0f03600-50a1-11e9-9dff-3ca9967079fc.png)

**Comment by langsmith** [comment]
Closing because I've never experienced this crash. It was seen against Maps SDK version `7.3.0` and now we're on `8.3.0`. I'm going to assume our Maps SDK improvements have covered this 🐛 . Happy to re-open if someone feels there's an avenue to investigate.
