### ISSUE TITLE
Not working on Android 8.1.0

### ISSUE THREAD

**Issue by Qirtas** [mapbox/mapbox-android-demo#1008]
Demo app not working on Android 8.1.0 but it's working fine on older versions. I can see only blank screen on Android Oreo like below. 
![Screenshot_20190331-095739_Mapbox Demo](https://user-images.githubusercontent.com/21234281/55377668-6b16f000-552f-11e9-8856-573eb37dae21.jpg)
![Screenshot_20190331-095731_Mapbox Demo](https://user-images.githubusercontent.com/21234281/55377673-6d794a00-552f-11e9-98a0-f92276eec33d.jpg)

**Comment by LukasPaczos** [comment]
Hey @Qirtas, is the date on your device correct? It seems like a certificate issue.

**Comment by Qirtas** [comment]
@LukasPaczos Yes, it was wrong date issue. Maps are working fine now. Thanks

**Comment by altafc22** [comment]
same issue in my case, in my device date is correct still map is not showing
