### ISSUE TITLE
Can we update zoom level dynamicly ?

### ISSUE THREAD

**Issue by zongyunfeng** [mapbox/mapbox-android-demo#1034]
![2019-04-17 12 24 27-min](https://user-images.githubusercontent.com/14245113/56262042-c3ddaf80-610f-11e9-95c8-40c6b3381800.gif)
We noticed an amazing animation in the ios demo which updates the camera(especially the zooming) in an `AccelerateDecelerateInterpolator` manner，Can we implement this with Mapbox Android SDK?

**Comment by langsmith** [comment]
Hi @zongyunfeng , thanks for looking into Mapbox. This is possible with the Mapbox Maps SDK for Android.

See the `AnimateMapCameraActivity` in this demo app: https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/camera/AnimateMapCameraActivity.java

![ezgif com-resize](https://user-images.githubusercontent.com/4394910/56266875-226c4480-60a2-11e9-93c7-14407113f6b6.gif)

You could hook a ValueAnimator that has whatever interpolator(s) you want, into to the `CameraPosition` class and `animateCamera()`/ `easeCamera()`.
