### ISSUE TITLE
CircleLayerCluster example: filter limit on green color not considering equal

### ISSUE THREAD

**Issue by martinKindall** [mapbox/mapbox-android-demo#1048]
https://github.com/mapbox/mapbox-android-demo/blob/162f46d0df0c7d4ad1d548cd567e210892a8e045/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java#L211

On line L211, the condition must be greater than, otherwise when the cluster has the exact quantity of the filter limit, it is going to be colorless (already experienced it).

--->    gte(pointCount, literal(layers[i][0])),
          lt(pointCount, literal(layers[i - 1][0]))

**Comment by langsmith** [comment]
Thanks for the ticket and for using Mapbox, @martinKindall . 

> the condition must be greater than

Did you mean  _greater than or equal_ ?  That's what your code snippet appears to use with the `gte`. Line 211 in the `master ` branch is already using _greater than_ ( `gt` ).

**Comment by martinKindall** [comment]
@langsmith Yes! I meant greater than or equal.
