### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by hansandroid** [mapbox/mapbox-android-demo#1053]
Hello, how can I cluster the markers if I use the symbolmanager and symbols?

**Comment by langsmith** [comment]
Thanks for using Mapbox, @hansandroid. The Annotation Plugin doesn't support clustering at this time. Please see the following links to learn how to do clustering with `SymbolLayers` icons:

https://docs.mapbox.com/android/maps/examples/symbol-layer-clustering/

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ImageClusteringActivity.java
