### ISSUE TITLE
Maps SDK v7.5.0

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-android-demo#1056]
- [x] v7.5.0-alpha.2
- [ ] v7.5.0-beta.1
- [ ] v7.5.0

**Comment by osana** [comment]
No issues found in 7.5.0-alpha.1

**Comment by LukasPaczos** [comment]
Thanks @osana for running with the QA! Could you convert this issue to a PR, similarly to https://github.com/mapbox/mapbox-android-demo/pull/1019?

**Comment by osana** [comment]
Converted this issue to PR: https://github.com/mapbox/mapbox-android-demo/pull/1061
