### ISSUE TITLE
Marker Source Already Present issue while updating maker on Mapbox map

### ISSUE THREAD

**Issue by kamleshsahu** [mapbox/mapbox-android-demo#1058]
i am using mapbox maps sdk in android and updating the UI with (1000+)markers at some interval of time.By updating i mean (removing all the markers and then again placing with new data).But sometimes when the removal process of marker is not finished,my function starts overwriting the marker again which throws the error as marker is already present. Is there any method by which track the complition of my UI task??just like onPostExecute is for AsyncTask. I just want to trigger my marker placing function after removing all old markers.

**Comment by tobrun** [comment]
not sure if I fully understand your issue. Having some code to reproduce would help a lot to get to the bottom of this.

**Comment by langsmith** [comment]
Hey thanks for using Mapbox, @kamleshsahu . I'm going to close this because haven't heard back from you. We're more than happy to re-open this and keep the conversation going once we get a response from you. Some code to reproduce the issue would be great.
