### ISSUE TITLE
Location picker marker icon not anchored correctly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#107]
When selecting a location and then zooming in or out the location currently moves. This is because we are currently using the default marker and it isn't anchored properly. The snippet where the error occurs can be [found here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/LocationPickerActivity.java#L120-L127).

**Comment by chewbyte** [comment]
I'm so glad someone else is having this issue, I was going insane today thinking I was doing something wrong.

From my experiments the .anchor(float u, float v) method for MarkerViewOptions isn't currently working, and playing with the values will result in no change in the position of the icon.
