### ISSUE TITLE
Compass Clips Intermittently when Rotating Map

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-android-demo#1079]
### What's wrong
When rotating the map in some of the examples, the compass in the upper right hand corner will be clipped seemingly at random:

![image](https://user-images.githubusercontent.com/16272584/58215627-c8762480-7cc8-11e9-89c6-ddbb8cfe2bad.png)

### Expected behavior
No clipping, please ✂️🙅‍♂ 

### Actual behavior
Quite a bit of clip! 

cc: @langsmith

**Comment by tobrun** [comment]
Could we validate if this issue is reproducible with TextureView?

**Comment by langsmith** [comment]
`mapbox:mapbox_renderTextureMode="true"` seems to solve the clipping issue. Turned on layout bounds display for better insight into where the boundaries are.

**Without TextureView:**

![ezgif com-resize (5)](https://user-images.githubusercontent.com/4394910/58371250-89142780-7ec4-11e9-9c9d-bc3ac3865293.gif)

**With TextureView:**

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/4394910/58371275-d7c1c180-7ec4-11e9-9868-fdaaf4996a4b.gif)

**Comment by langsmith** [comment]
Considering resolved. Feel free to re-open if you feel differently.
