### ISSUE TITLE
com.mapbox.mapboxandroiddemo.R missing

### ISSUE THREAD

**Issue by saktani** [mapbox/mapbox-android-demo#1080]
In the project it can't find this import 
import com.mapbox.mapboxandroiddemo.R;
where can I find this file?

thank you

**Comment by tobrun** [comment]
R files are automatically generated https://stackoverflow.com/questions/4953077/what-is-the-class-r-in-android. You will need to rebuild the project to generate one.

**Comment by Avishak-2017831010** [comment]
I am facing the same problem. Can you help with the solution?

**Comment by cozian1** [comment]
Did anyone foud solution for this
