### ISSUE TITLE
when map is tilted fit bounds not work properly

### ISSUE THREAD

**Issue by PhloxDev** [mapbox/mapbox-android-demo#1110]
when map is tilt fit somewhere else and not work properly.

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/23661966/59465208-98d9b880-8e3f-11e9-9652-fdb20a7c6479.gif)

### Configuration

**Android versions:6.0.1** 
**Device models:j7** 
**Mapbox SDK versions:8.0.1**

**Comment by tobrun** [comment]
Thank you both for reaching out, we are aware that the CameraUpdateFactory LatLngBounds methods are corretcly working. For this to properly work, please use the following instead:

```
MapboxMap.getCameraForLatLngBounds(LatLngBounds, padding, tilt, bearing) 
```

and use the retrieved camera position with the CameraUpdateFactory. 

Let's keep this issue open until we fix the [example code]( https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/camera/BoundingBoxCameraActivity.java#L102).

**Comment by tobrun** [comment]
apologies, this is actually a bug in maps sdk, fix in https://github.com/mapbox/mapbox-gl-native/pull/14953/files

**Comment by tobrun** [comment]
one follow here, is that behaviour described in this issue is a works as designed. If you want to have the same bounds always you need to use the new `CameraUpdateFactory#newLatLngBounds(bounds, 0 /*bearing*/, 0 /*tilt*/, padding);`
