### ISSUE TITLE
Draggable Marker in Android

### ISSUE THREAD

**Issue by asifjavaid** [mapbox/mapbox-android-demo#1126]

**Comment by asifjavaid** [comment]
Hi,

We are using Mapbox Android SDK. We need to implemented draggable marker. Do we have any way to implement it in the new mapbox sdk.?

Thank you.

**Comment by langsmith** [comment]
Hey @asifjavaid , thanks for using Mapbox!

The easiest way to implement marker dragging is via the Mapbox Annotation Plugin for Android https://docs.mapbox.com/android/plugins/overview/annotation/

The Mapbox demo app has a SymbolListener example: https://docs.mapbox.com/android/plugins/examples/symbol-listener:
  - Found here: https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/SymbolListenerActivity.java )

The plugin test app also has a Symbol activity which shows listening for dragging: https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/SymbolActivity.java

**Comment by asifjavaid** [comment]
Hey @langsmith , Wow I am very thank full for you prompt response. :) let me try.

**Comment by asifjavaid** [comment]
Hey @langsmith . I have implemented draggable marker. I need two more questions.
1. Can we use our own custom icons instead of Maki icons?
2. Can we show our big images on calloutView onClick event of Marker/Symbol?

Notes: I also have some more questions regarding mapbox android and open new issues, but no one is answering. Should i need to continue this single thread or do you people need a paid account for prompt replys as we are getting late in our deadlines?

Thank you.

Asif.

**Comment by langsmith** [comment]
> 1. Can we use our own custom icons instead of Maki icons?

Yes, if you add the images to the map style before using the unique ID for that image.  
For example:

```java
 @Override
  public void onMapReady(@NonNull final MapboxMap mapboxMap) {
    mapboxMap.setStyle(Style.MAPBOX_STREETS, new Style.OnStyleLoaded() {
      @Override
      public void onStyleLoaded(@NonNull Style style) {


        style.addImage("CUSTOM_IMAGE", BitmapUtils.getBitmapFromDrawable(getResources().getDrawable(R.drawable.red_marker)));
       
        style.addImage("SECOND_CUSTOM_IMAGE", BitmapUtils.getDrawableFromRes(SymbolListenerActivity.this, R.drawable.ic_business));

....

        symbol = symbolManager.create(new SymbolOptions()
            .withLatLng(new LatLng(60.169091, 24.939876))
            .withIconImage("CUSTOM_IMAGE")
            .withIconSize(2.0f)
            .withDraggable(true));

....

 // Add click listener and change the symbol to a cafe icon on click
        symbolManager.addClickListener(new OnSymbolClickListener() {
          @Override
          public void onAnnotationClick(Symbol symbol) {
            symbol.setIconImage("SECOND_CUSTOM_IMAGE");
            symbolManager.update(symbol);
          }
        });

```

2. Can we show our big images on calloutView onClick event of Marker/Symbol?

I'm not sure what you mean. You want to increase the size of the image when it's clicked? 

```java
symbolManager.addClickListener(new OnSymbolClickListener() {
          @Override
          public void onAnnotationClick(Symbol symbol) {
            symbol.setIconSize(float newSize);
            symbolManager.update(symbol);
          }
        });
```

Or you want to show a big image in a separate "Info Window" ([like this](https://docs.mapbox.com/android/maps/examples/symbol-layer-info-window/)) when the marker is clicked?

> Notes: I also have some more questions regarding mapbox android and open new issues, but no one is answering. Should i need to continue this single thread or do you people need a paid account for prompt replys as we are getting late in our deadlines?

The Android team is managing several repos, projects, and SDKs. We do try to attend to folks on Github, but contacting our Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 is best if you have questions about _implementing_ Mapbox into your project. 

I believe there are upcoming changes around support options/pricing, but I don't have the specifics. You can contact our Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 if you have questions around support options.

**Comment by asifjavaid** [comment]
Hi @langsmith,

Thank you for your response.

Your above solution is working great. And yes we do need to show big image in "Info Window" on marker by lazy loading using Glide or Picasso libraries. On the click event of image in "Info Window" we want to open full view of that image... Is it possible with Symbol Manager in Mapbox? Otherwise we want to show only MarkerName in the Info Window.

Thank you.

![Uploading image.png…]()

**Comment by asifjavaid** [comment]
Hi @langsmith 
I am following this url for Info Window:
[https://docs.mapbox.com/android/maps/examples/symbol-layer-info-window/](url)

I am adding the following properties to display name, and selection of marker.

`List<Point> listPoint = new ExCollection<>();
                listPoint.add(markerPoint);
                Feature[] features = new Feature[] {Feature.fromGeometry(
                        LineString.fromLngLats(listPoint)
                )};
                features[0].addStringProperty(PROPERTY_NAME,mPoint.getName());
                features[0].addBooleanProperty(PROPERTY_SELECTED, false);

                featureCollection = FeatureCollection.fromFeatures(features);
                setUpData(featureCollection);
                new GenerateViewIconTask(ViewMapActivity.this).execute(featureCollection);
`
But name property is not exists in the render *feature* from the function 'getMapBox().queryRenderedFeatures(screenPoint)'

Here is the same code I am using:

`private boolean handleClickIcon(PointF screenPoint) {
        List<Feature> features = getMapBox().queryRenderedFeatures(screenPoint);
        if (!features.isEmpty()) {
            String name = features.get(0).getStringProperty(PROPERTY_NAME);
            List<Feature> featureList = featureCollection.features();
            for (int i = 0; i < featureList.size(); i++) {
                if (featureList.get(i).getStringProperty(PROPERTY_NAME).equals(name)) {
                    if (featureSelectStatus(i)) {
                        setFeatureSelectState(featureList.get(i), false);
                    } else {
                        setSelected(i);
                    }
                }
            }
            return true;
        } else {
            return false;
        }
    }`

Please let me know how can I get the name property so that the Info window should display successfully on Map Click on  Icon/Marker.

Here is the debug information.
![mapbox_marker](https://user-images.githubusercontent.com/5367376/60906245-25856400-a290-11e9-92ac-70a3f31a27dd.png)

Thank you.

**Comment by langsmith** [comment]
You should query the marker layer inside of `queryRenderedFeatures()`. The layer id should be the second parameter

`List<Feature> features = getMapBox().queryRenderedFeatures(screenPoint,MARKER_LAYER_ID);`

**Comment by asifjavaid** [comment]
@langsmith 
I did the same now. But still same response. Event I tap on the marker, it become invisible.

Here is the screenshot of debug mode.
![mapbox_marker](https://user-images.githubusercontent.com/5367376/60923090-9be98c80-a2b7-11e9-9fab-1647b2051592.png)
