### ISSUE TITLE
Begin work on next release examples

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#115]
The next release of the MAS and Mapbox Android SDK will include new features we will need to demonstrate in this app. Using this ticket to track what examples should be added:

## Style examples:
- [x] [Heatmap example](https://www.mapbox.com/mapbox-gl-js/example/heatmap/)
- [x] [Show and hide layers](https://www.mapbox.com/mapbox-gl-js/example/toggle-layers/)
- [x] [Add a vector tile source](https://www.mapbox.com/mapbox-gl-js/example/vector-source/)
- [x] [Change a maps language](https://www.mapbox.com/mapbox-gl-js/example/language-switch/)
- [x] [Change a layer's color with buttons](https://www.mapbox.com/mapbox-gl-js/example/color-switcher/)
- [x] [Add a new layer below labels](https://www.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/)
- [x] ~~[Add an image](https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/)~~
- [x] ~~[Add a video](https://www.mapbox.com/mapbox-gl-js/example/video-on-a-map/)~~
- [x] ~~[Update a choropleth layer by zoom level](https://www.mapbox.com/mapbox-gl-js/example/updating-choropleth/)~~
- [x] [Adjust a layer's opacity](https://www.mapbox.com/mapbox-gl-js/example/adjust-layer-opacity/)
- [x] Ivo's zoom level changes layer fill color (examples in testapp already) <img src=http://cultofthepartyparrot.com/parrots/parrot.gif />

## User location:
- [x] Animated user location pulsing
- [x] Basic user location example fix
- [x] [user location icon customation (padding)](https://github.com/mapbox/mapbox-gl-native/issues/5977)

## [Map Features](https://github.com/mapbox/mapbox-gl-native/issues/352#issuecomment-233281686)
- [x] Select a building
- [x] [Bounding box query](https://github.com/mapbox/mapbox-gl-native/issues/5869#issuecomment-239817496)

## ~~Clustering:~~
- [x] ~~[Create and style clusters](https://www.mapbox.com/mapbox-gl-js/example/cluster/)~~

## Offline:
- [x] ~~[SD Storage](https://github.com/mapbox/mapbox-android-demo/pull/122)~~

## Marker view
- [x] [Scaling circle](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewScaleActivity.java)

## MAS example:
- [x] ~~[measure distance](https://www.mapbox.com/mapbox-gl-js/example/measure/)~~

## Labs:
- [x] [toggle land use layer colors](https://github.com/mapbox/mapbox-android-demo/pull/124)

Let me know if I'm missing something, you'd like to see an example not listed here, or something listed here isn't possible.

cc: @ivovandongen @zugaldia @bleege @tobrun @danswick @lyzidiamond

**Comment by zugaldia** [comment]
I'd add `featuresAt` to the list https://github.com/mapbox/mapbox-gl-native/issues/352#issuecomment-233281686.

**Comment by cammace** [comment]
Also adding marker view circle scaling to the list of examples to be added, similar to the [one found in the testapp](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewScaleActivity.java). 

cc: @incanus

**Comment by cammace** [comment]
Changing a language example: 
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/17370279/6b3a1bf8-5969-11e6-81b6-bf03fe7a4ba8.gif)
refreshing tiles when switching language doesn't currently happen, [ticketed here](https://github.com/mapbox/mapbox-gl-native/issues/5701), examples finished however.

**Comment by cammace** [comment]
Adjust a raster layers opacity examples finished. Same bug exist as mentioned above along with the wrong tile size bug? I opened a [ticket about this here](https://github.com/mapbox/mapbox-gl-native/issues/5856):
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/5652865/17375275/4067c19a-597e-11e6-9a97-95006cbf39f5.gif)

**Comment by cammace** [comment]
toggle layer visibility (currently suffers from [bug found here](https://github.com/mapbox/mapbox-gl-native/issues/5849)):

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/5652865/17375739/49469e1a-5980-11e6-93b4-d98d0b2a2551.gif)

**Comment by cammace** [comment]
Add a vector layer example finished (same shader bug as mentioned above):

![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/5652865/17375946/4711d334-5981-11e6-9fed-b49b92a0f9a3.gif)

**Comment by cammace** [comment]
@ivovandongen's insane layer fill color dependent on zoom level example:

![ezgif com-video-to-gif 5](https://cloud.githubusercontent.com/assets/5652865/17379929/88f18a18-5992-11e6-8e57-89cfaf9c7ed4.gif)

<img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif /><img src=http://cultofthepartyparrot.com/parrots/parrot.gif />

**Comment by zugaldia** [comment]
@cammace Merge it already.

**Comment by cammace** [comment]
Finished the "Add a new layer below labels" example:
<img src="https://cloud.githubusercontent.com/assets/5652865/17381833/0e37cdfa-599c-11e6-974c-d3d5e935b79f.png" width=360 />

as well as the "Change a layer's color with sliders":
![ezgif com-video-to-gif 6](https://cloud.githubusercontent.com/assets/5652865/17382003/cbf9beb6-599c-11e6-9bfa-ddee610d6746.gif)

**Comment by pveugen** [comment]
This is so good. 🔥 🔥 🔥

**Comment by cammace** [comment]
I've started work on the next labs activity show casing how to style certain map features such as parks and schools:

![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/5652865/17636500/78dfa09a-60ab-11e6-9a30-4d8b14a0c4c4.gif)

**Comment by tobrun** [comment]
Nice!

**Comment by zugaldia** [comment]
@cammace Another good example to consider, from @ivovandongen https://github.com/mapbox/mapbox-gl-native/issues/5869#issuecomment-239817496.

**Comment by cammace** [comment]
New user location example (Frequently asked how to do) and fixed basic user location issue #83:

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5652865/17680136/bdae0cc6-630c-11e6-83e7-aa815c8b3ff1.gif)

**Comment by cammace** [comment]
Point clustering to make a heatmap example:

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/5652865/17713245/ede0579e-63c7-11e6-9b64-9f897e6a7e6c.gif)

**Comment by incanus** [comment]
> @ivovandongen's insane layer fill color dependent on zoom level example:

While this is amazing, it's not very practical and I'm wondering if we can do something more so. Right now we're blocked by https://github.com/mapbox/mapbox-gl-native/issues/5701 for some more fine-grained runtime styling possibilities, but the transit demo I'm working on could be a good fit.

**Comment by cammace** [comment]
No need to remove the example in the demo app though, plenty of room for as many examples 😄. Even if https://github.com/mapbox/mapbox-gl-native/issues/5701's blocking a few examples, i'd go ahead and create them, the `Change a map's language` example has this issue. Is there a ticket somewhere to checkout the transit demo? Really looking forward to it!

**Comment by incanus** [comment]
> No need to remove the example in the demo app though, plenty of room for as many examples

👍 

>  Is there a ticket somewhere to checkout the transit demo? 

No, it's really ready for ticket yet until I can play a bit more in runtime styling code to get the picture in my head. As soon as I can unblock this I'll ticket it up to run it out to completion.

**Comment by cammace** [comment]
Landuse examples now complete finishing off this ticket.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5652865/17909559/00c56c2e-6953-11e6-904d-48c0c33cae04.gif)

**Comment by zugaldia** [comment]
@cammace This list of examples is amazing. Showing off the demo app is such a joy.
