### ISSUE TITLE
how can we view 3D map

### ISSUE THREAD

**Issue by asifjavaid** [mapbox/mapbox-android-demo#1151]
Hi,

We are using this code "BuildingPluginActivity.java" for 3D display of buildings. We did just exactly copy and paste but the map is simple, there is no 3D view. Can you please guide us how can see the 3D view?

Thank you.

--
Regards,
Asif.

**Comment by langsmith** [comment]
Hi @asifjavaid , `BuildingPluginActivity.java` is working fine on `master` of this demo app. What map style are you using? Any code that you can share here?

**Comment by langsmith** [comment]
Closing because I haven't heard a response back. More than happy to re-open and continue the conversation.
