### ISSUE TITLE
MapSnapshotter will not include custom layer

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-android-demo#1156]
Add a custom layer before snapshot, there will be white cycles on top of map.
![device-2019-08-01-151519](https://user-images.githubusercontent.com/8577318/62273071-37ad8900-b46f-11e9-9d03-97a460e0cbd5.png)

Then take snapshot and the snapshot image will not include this layer.
![share_image_1564644030511](https://user-images.githubusercontent.com/8577318/62273429-2618b100-b470-11e9-9db9-0239f95a5104.png)

The test codes have been uploaded to branch `kl-screenshot`.
Open the test app and then go to `Image generation`, `Share snapshot image` and then click the button will reproduce this issue.

The same issue can be found on iOS.
cc: @tmpsantos

**Comment by langsmith** [comment]
Yes, runtime custom layers aren't currently an option for the map snapshotter. cc @chloekraw https://github.com/mapbox/mapbox-gl-native/issues/9914

I'm going to close this ticket because this isn't an issue specific to this demo app.
