### ISSUE TITLE
Add Text in LineLayer

### ISSUE THREAD

**Issue by asifjavaid** [mapbox/mapbox-android-demo#1157]

**Comment by asifjavaid** [comment]
Hi Guys,

I am using LineLayerActivity.java code for my app. Can we add Text in the center of LinerLayer?
I am using the following properties but no effect.
```

PropertyFactory.textField("Text Field"),
                PropertyFactory.textAnchor(Property.TEXT_ANCHOR_CENTER),
                PropertyFactory.textColor(getResources().getColor(R.color.app_color_red_transparent)),
                PropertyFactory.textSize(16.0f),
                PropertyFactory.lineWidth(2f),
```

--
Regards,
Asif Javaid.

**Comment by langsmith** [comment]
@asifjavaid , you'll want to use `symbolPlacement(SYMBOL_PLACEMENT_LINE)` on a `SymbolLayer`. Make sure that the `SymbolLayer` and `LineLayer` share the same data source (id). 

You can see this in action in the `IsochroneActivity`. The ischrone minute ranges text is placed exactly on each isochrone contour line:
- https://docs.mapbox.com/android/java/examples/isochrone
- https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/IsochroneActivity.java#L273
