### ISSUE TITLE
How do I check particular LatLng belong to polygon ?

### ISSUE THREAD

**Issue by manishpatelgt** [mapbox/mapbox-android-demo#1189]
How do I check particular LatLng belong to polygon ?

I am using below sdk in Android

` implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.1'`

**Comment by langsmith** [comment]
Hey @manishpatelgt , thanks for using Mapbox.

You can use the Java port of [the `pointsWithinPolygon()` Turf method](http://turfjs.org/docs/#pointsWithinPolygon):

- https://github.com/mapbox/mapbox-android-demo/search?q=TurfJoins&unscoped_q=TurfJoins

You can use a certain coordinate to query whether it's in `FillLayer`'s polygon:

- https://docs.mapbox.com/android/maps/overview/query/

- https://github.com/mapbox/mapbox-android-demo/search?q=queryRenderedFeatures&unscoped_q=queryRenderedFeatures

**Comment by manishpatelgt** [comment]
Thanks @langsmith 
Let me try
