### ISSUE TITLE
Update to Android 4.2.0-beta.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#119]
We released the [Android 4.2.0-beta.1](http://search.maven.org/#artifactdetails%7Ccom.mapbox.mapboxsdk%7Cmapbox-android-sdk%7C4.2.0-beta.1%7Cjar) on maven central.
Time to update the demo app with this release.

cc @cammace

**Comment by cammace** [comment]
Finishing up the style API examples now, will merge and then we can release.
