### ISSUE TITLE
Draw a line/route as user moves

### ISSUE THREAD

**Issue by saddahussain** [mapbox/mapbox-android-demo#1194]
Need to draw the route/line as the user moves, just like uber, it creates the route dynamically as the user moves. Let me know if more information is needed. I have completed this thing on Google Maps using poly lines. Just want to know this feature could be done using MapBox.

**Comment by saddahussain** [comment]
[https://ichef.bbci.co.uk/news/624/media/images/83258000/jpg/_83258776_uber4.jpg](url) Something like this.

**Comment by langsmith** [comment]
Hi @saddahussain , thanks for looking into Mapbox.

This can definitely be done with Mapbox. https://docs.mapbox.com/android/maps/examples/moving-icon-with-trailing-line/ is probably the closest example to what you're looking for. There's also https://docs.mapbox.com/android/maps/examples/marker-following-route.

**Comment by saddahussain** [comment]
Line behind moving icon is exactly what I am trying to do. Don't know how I missed its documentation. So silly of me. Thanks a lot. Highly appreciated.
