### ISSUE TITLE
Simplify Polyline 

### ISSUE THREAD

**Issue by saddahussain** [mapbox/mapbox-android-demo#1197]
I have a list of points and I am drawing a polyline using that list. Now I want to convert that polyline to an optimized/simplified route. I have checked Simplify a polyline example from official documentation https://docs.mapbox.com/android/java/examples/simplify-a-polyline/. But that uses a feature collection to draw simplified lines. Is there any way that I could use the list of points to simplify the polyline or if I could convert the points to feature collection.

**Comment by langsmith** [comment]
I'd highly recommend you convert the `Point`s into a `FeatureCollection` so that you can fully benefit from the Mapbox Map Matching API: https://docs.mapbox.com/android/java/overview/map-matching/


```java
List<Feature> featureList = new ArrayList<>();
Point pointObject = Point.fromLngLat(longitude,latitude);
// loop through your list of points and create a Feature and add to the Feature list 
Feature singleFeature = Feature.fromGeometry(pointObject);
featureList.add(singleFeature);
FeatureCollection.fromFeatures(featureList);
```
