### ISSUE TITLE
How do I show current location marker without moving camera position ?

### ISSUE THREAD

**Issue by manishpatelgt** [mapbox/mapbox-android-demo#1203]
I am creating LatLngBounds with 3 points. One of the point is user current location.
So as soon as i land in map screen LatLngBounds is not working and not fit all the three points in max zoom bounds due to location engine directly move camera zoom to my current location.

 I want to show all three with max zoom bounds + current location (without moving camera to this location)
. So my question is **How do I show current location marker without moving camera position ?**

I am using below SDK in my Android project

`  implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.1'`

**Comment by LukasPaczos** [comment]
Hey @manishpatelgt, what type of `CameraMode` are you using? If you don't want the location component to track the location, you should use `CameraMode.NONE`. Please refer to [the docs](https://docs.mapbox.com/android/maps/overview/location-component/#cameramode). I hope this helps!

**Comment by manishpatelgt** [comment]
@LukasPaczos I am using CameraMode.TRACKING. let me try to let NONE

**Comment by manishpatelgt** [comment]
@LukasPaczos Thank you. It worked like charm!
