### ISSUE TITLE
Adding/Removing Mapbox Source and Layers.

### ISSUE THREAD

**Issue by saddahussain** [mapbox/mapbox-android-demo#1204]
I am doing live tracking of user on map and am drawing a line by adding a line-layer on map. Now I have to update the line as user moves around. For now what I do is, as soon as I get location update I first remove the source and layer and then update them again. I do this on every location update. I don't think this is an efficient way of doing that. Is there any way I can update the source and layers without adding removing them again and again.

here is the code snippet

 ```
                style.removeLayer("linelayer")
                style.removeSource("line-source")

                style.addSource(
                    GeoJsonSource(
                        "line-source",
                        FeatureCollection.fromFeatures(
                            arrayOf<Feature>(
                                Feature.fromGeometry(
                                    LineString.fromLngLats(coordinatesList!!.toPointsList())
                                )
                            )
                        )
                    )
                )

                style.addLayer(
                    LineLayer("linelayer", "line-source").withProperties(
                        PropertyFactory.lineCap(Property.LINE_CAP_ROUND),
                        PropertyFactory.lineJoin(Property.LINE_JOIN_ROUND),
                        PropertyFactory.lineWidth(5f),
                        PropertyFactory.lineColor(Color.parseColor("#69b144"))
                    )
                )
```

**Comment by langsmith** [comment]
Please contact our Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 for Mapbox implementation questions. Tickets in this repo are for issues with this specific demo app.
