### ISSUE TITLE
Move or animate symbol using Symbol Manager

### ISSUE THREAD

**Issue by saddahussain** [mapbox/mapbox-android-demo#1205]
I have added a symbol(marker) on mapView. How can we move or animate symbol on map using symbol manager.

Here is the symbol

               endSymbol = symbolManager.create(
                SymbolOptions()
                    .withLatLng(LatLng(userLocation!!.lat, userLocation!!.long))
                    .withIconImage("END_ICON")
                    .withIconSize(1f)
              )

**Comment by saddahussain** [comment]
I really do no want to delete and create the symbol again.

**Comment by langsmith** [comment]
Please contact our Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 for Mapbox implementation questions. Tickets in this repo are for issues with this specific demo app.
