### ISSUE TITLE
How can I get cities and states of a country with zip_code?

### ISSUE THREAD

**Issue by eslam2010011** [mapbox/mapbox-android-demo#1207]

**Comment by langsmith** [comment]
Hi @eslam2010011 , thanks for using Mapbox.

Please see the following links and then contact our Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 for Mapbox implementation questions. Tickets in this repo are for issues with this specific demo app.

- https://docs.mapbox.com/android/plugins/overview/places#search-options
- https://docs.mapbox.com/help/how-mapbox-works/geocoding/
- https://docs.mapbox.com/android/java/examples/geocoding/
