### ISSUE TITLE
Saving user-added data to Shared Preferences

### ISSUE THREAD

**Issue by Presidente27** [mapbox/mapbox-android-demo#1209]
It would be great to see an example of any changes done by the user during runtime (like marking the favourite places in demo Lab/SymbolLayer icons) being put into Shared Preferences, to prevent them from dissapearing after closing the app. Cheers!

**Comment by langsmith** [comment]
Thanks for the suggestion @Presidente27 .  I opened #1210 to show how to save and retrieve coordinate numbers. You can save a good amount of different information in shared preferences:

![Screen Shot 2019-09-16 at 11 11 10 AM](https://user-images.githubusercontent.com/4394910/64982300-b8cfac80-d872-11e9-9bbe-f50c2afcc5c8.png)

Related links:
https://developer.android.com/guide/topics/data/data-storage
https://developer.android.com/training/data-storage/shared-preferences
