### ISSUE TITLE
Map not displaying on demo application - HTTP status code 401

### ISSUE THREAD

**Issue by Pedestal19** [mapbox/mapbox-android-demo#1219]
I tried running  the demo application but the map does not display, neither does the location. I checked my log and saw this: 

{droiddemo.debug}[Setup]: loading style failed: HTTP status code 401

![mapbox401](https://user-images.githubusercontent.com/22978976/65256421-69e67900-daf7-11e9-946e-77fd843dedf4.JPG)

**Comment by langsmith** [comment]
Hey @Pedestal19 , thanks for using the app.

You've entered your access token (https://github.com/mapbox/mapbox-android-demo#running-locally), correct? You're running the `global` flavor (https://github.com/mapbox/mapbox-android-demo#product-flavors), correct? 

What map style are you trying to load? A default Mapbox one (e.g. Streets, Dark, etc.)? If it's your custom style, can you share the map style URL that you're trying to use?

**Comment by Pedestal19** [comment]
Hello @langsmith , thanks for the reply.

Yes, I am running the global flavor, I also tried the china flavor too. I have generated an access token on my mapbox dahboard, and I am using it in the app. I am trying to display a default map, and also looking to explore the offline maps capabilities of mapbox.

**Comment by langsmith** [comment]
So strange. You're on `master`? What happens when you open the most basic example in the demo app (`SimpleMapViewActivity`)? The app doesn't crash and the map tiles/style don't load but you still see the Mapbox logo name in the lower left hand corner?

**Comment by Pedestal19** [comment]
Hello @langsmith ,

Yes I am on master and the mapbox logo is at the lower left hand corner. After several tries, I discovered something. I found out that after I did a clean rebuild and used my public key(pk), the map started working. However, It doesn't work with my secret key(sk) even after giving it all the permissions.

**Comment by langsmith** [comment]
Glad that you got it working with the public key.
