### ISSUE TITLE
Create example showing how to explore cluster data

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#1220]
The Maps SDK for Android has several helpful methods for exploring clustered information. 

![Screen Shot 2019-09-19 at 2 35 54 PM](https://user-images.githubusercontent.com/4394910/65282964-12421080-daeb-11e9-99f1-b117951edb75.png)

Could be good to make 1-2 examples that show how to retrieve/see information based on tapping on clusters.

cc @liannamartin1

**Comment by adrianababakanian** [comment]
Noting that this is closely related to https://github.com/mapbox/mapbox-android-demo/issues/1085.

**Comment by langsmith** [comment]
Resolved by https://github.com/mapbox/mapbox-android-demo/pull/1301
