### ISSUE TITLE
Mapview inside fragment doesn't work

### ISSUE THREAD

**Issue by navdeepg** [mapbox/mapbox-android-demo#1226]
Hey Team,

I am trying to add mapview inside a fragment and not activity. It keeps showing me blank screen without any error. Can you provide me some working example? There is no example in mapbox sdk git project for fragment. Any help would be much appreciated

.

Thanks,
Navdeep

**Comment by navdeepg** [comment]
Any update here?

**Comment by LukasPaczos** [comment]
@navdeepg here's a [`SupportMapFragment`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/basics/SupportMapFragmentActivity.java) example. [Here](https://github.com/mapbox/mapbox-gl-native/blob/d446b3382b7de03d9031445e37c1ebf183092ea2/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/BottomSheetActivity.java#L208-L281)'s also an example of a standalone fragment implementation. Closing as answered, please let us know if that wasn't what you're looking for.
