### ISSUE TITLE
地图截图怎么包含marker和line

### ISSUE THREAD

**Issue by xhAndroid** [mapbox/mapbox-android-demo#1250]
SDK-v6.8.1版本
怎么调用mapbox的截图功能，包含markers和line ？
示例的demo截图只截取了底图，没有包含地图打点和线。

**Comment by langsmith** [comment]
请看 [`SnapshotShareActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/snapshot/SnapshotShareActivity.java#L109).  你开始`mapSnapshotter`之前，你可以用:

```java
mapboxMap.getStyle(new Style.OnStyleLoaded() {
  @Override
  public void onStyleLoaded(@NonNull Style style) {
       mapSnapshotter.setStyleJson(style.getJson());
}
});
```

或者 👇 . 通过Mapbox Studio先对你地图加markers和line, 然后:

```java
mapSnapshotter.setStyleUrl(STYLE_URL);
``` 

cc @Chaoba

**Comment by langsmith** [comment]
有更多问题的话，就告诉我。谢谢你使用Mapbox！

**Comment by xhAndroid** [comment]
@langsmith 您好，看过mapbo的官方文档，https://docs.mapbox.com/android/maps/overview/snapshotter/#taking-a-map-snapshot
这样是可以截取到地图的底图。但是无法将在地图上打的marker、line一起截取上去。

**Comment by xhAndroid** [comment]
https://github.com/xhAndroid/DemoMapbox_v2
这是我的一个demo，可以截取地图底图，但是还是无法将marker、line一起截取。

**Comment by langsmith** [comment]
不好意思。看起来这支持票和https://github.com/mapbox/mapbox-android-demo/issues/1156#issuecomment-545192241 一样。现在，不能加这种的数据在地图上.

**Comment by Chaoba** [comment]
@xhAndroid snapshotter确实不支持这种功能，但是你可以试试[snapshot](https://docs.mapbox.com/android/api/map-sdk/8.2.0/com/mapbox/mapboxsdk/maps/MapboxMap.html#snapshot-com.mapbox.mapboxsdk.maps.MapboxMap.SnapshotReadyCallback-)

**Comment by xhAndroid** [comment]
public void snapshot(@NonNull
MapboxMap.SnapshotReadyCallback callback)
可以截取。

在 2019-10-23 10:49:29，"Kevin Li" <notifications@github.com> 写道：


@xhAndroid snapshotter确实不支持这种功能，但是你可以试试snapshot
