### ISSUE TITLE
MapView do not dispay

### ISSUE THREAD

**Issue by xiaoheixiaBry** [mapbox/mapbox-android-demo#1259]
When I replace the access token with my own access token , The map stil do not dispaly ,how can  I do ??

**Comment by langsmith** [comment]
Hi @xiaoheixiaBry , are you viewing the `globalDebug` build variant? https://github.com/mapbox/mapbox-android-demo#product-flavors

**Comment by langsmith** [comment]
@xiaoheixiaBry , were you able to figure this out? 

If you're trying to view China examples with the `chinaDebug` build variant, you should know that the `chinaDebug` flavor uses the Mapbox China Plugin for Android (https://www.mapbox.com/android-docs/plugins/overview/china). This plugin requires a special China Mapbox access token. Do you have a China access token? If not, please contact Mapbox via https://www.mapbox.com/contact/sales to start the process of receiving this special access token.

**Comment by langsmith** [comment]
Closing because I never heard back. Happy to re-open and keep chatting if I get a response.
