### ISSUE TITLE
 How to use online vector  tiles?

### ISSUE THREAD

**Issue by zhiwo** [mapbox/mapbox-android-demo#1261]
http://localhost:8088/geoserver/gwc/service/tms/1.0.0/myspace:mylayer@EPSG:900913@pbf/{z}/{x}/{y}.pbf

http://localhost:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=hmyspace:mylayer&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}

Is the url address using the second address?
Thank you very much for your reply. Does the official have a Demo?

**Comment by langsmith** [comment]
https://docs.mapbox.com/android/maps/examples/add-a-wms-source/ shows how to use a web map tiling service

Per https://gis.stackexchange.com/a/273471, looks like you'll want to use a `VectorSource`. A `VectorSource` is used several times in this demo app: https://github.com/mapbox/mapbox-android-demo/search?q=VectorSource&unscoped_q=VectorSource
