### ISSUE TITLE
I cant change the style after updating version from 5.2.0 to the latest version(8.4.0)

### ISSUE THREAD

**Issue by 549865602** [mapbox/mapbox-android-demo#1263]
Like i said,i used Mapview.setStyleUrl to load the style when i was in the version 5.2.0.Now i wanna update to the latest version.I found that i need to use MapboxMap.setStyle instead.But it doesnt work with the same URL......Want some help~Here is my URL:https://beidouim.oss-cn-hangzhou.aliyuncs.com/mob/map/map_m.json

**Comment by langsmith** [comment]
cc @chriswu @chaoba

![ezgif com-resize](https://user-images.githubusercontent.com/4394910/68698238-570b8600-0535-11ea-9c34-190e73048c91.gif)


The code below worked for me. I added `https://beidouim.oss-cn-hangzhou.aliyuncs.com/mob/map/map_m.json` to the app's `assets` folder.

```
 mapboxMap.setStyle(new Style.Builder().fromUri("asset://map_m.json"), new Style.OnStyleLoaded() {
       @Override
       public void onStyleLoaded(@NonNull Style style) {

       }
});
```

You should also know about Mapbox China!

http://mapbox.cn/

https://www.mapbox.com/android-docs/plugins/overview/china/

Here's our China Streets style:

![ezgif com-resize (2)](https://user-images.githubusercontent.com/4394910/68699346-b36fa500-0537-11ea-80c5-ce8d5a6c5c9f.gif)
