### ISSUE TITLE
How do i add custom marker with custom icon?

### ISSUE THREAD

**Issue by manishpatelgt** [mapbox/mapbox-android-demo#1268]
I tried to add custom marker but I am getting errors at line  **MarkerViewOptions()** in below code

Tried:

 ```
                       val icon = IconFactory.getInstance(this@HomeActivity)
                       icon.fromResource(R.drawable.ic_icon_person_marker)

                        // Add the marker to the map
                        mapboxMap?.addMarker(
                            MarkerViewOptions()
                                .position(latlng)
                                .icon(icon)
                        )
```
I am using dependency in android

` "com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.1"`

Where do i find tutorial for this ?

**Comment by langsmith** [comment]
You probably haven't installed the MarkerView plugin. Please see https://docs.mapbox.com/android/plugins/overview/markerview/#install-the-markerview-plugin

Just so you know, using sources & layers will look better on the map than `MarkerView`s: https://docs.mapbox.com/android/maps/overview/annotations/#source-and-layer

There's also the Annotation Plugin: https://docs.mapbox.com/android/plugins/overview/annotation/
