### ISSUE TITLE
The ChinaDebug Flavor does not display any maps

### ISSUE THREAD

**Issue by frankgogoland** [mapbox/mapbox-android-demo#1271]
I download the newest version. build the ChinaDebug flavor .It can not display any maps. thanks

**Comment by langsmith** [comment]
Hi @frankgogoland , thanks for looking into this demo app. 

The China debug flavor uses the Mapbox China Plugin for Android (https://www.mapbox.com/android-docs/plugins/overview/china). This plugin requires a special China Mapbox access token. Do you have a China access token? If not, please contact Mapbox via https://www.mapbox.com/contact/sales to start the process of receiving this special access token.

https://github.com/mapbox/mapbox-android-demo#setting-the-mapbox-access-token has instructions on how to set the Mapbox access token in this project.

**Comment by langsmith** [comment]
@frankgogoland, were you able to get the maps to display?

**Comment by frankgogoland** [comment]
Yes,I use Global Flavor branch instead




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Langston Smith"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 上午7:33
收件人:&nbsp;"mapbox/mapbox-android-demo"<mapbox-android-demo@noreply.github.com&gt;;
抄送:&nbsp;"冰冻三尺"<1223774014@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mapbox/mapbox-android-demo] The ChinaDebug Flavor does not display any maps (#1271)




@frankgogoland, were you able to get the maps to display?

**Comment by langsmith** [comment]
Ok
