### ISSUE TITLE
Camera tracking stops when mapview is touched or dragged

### ISSUE THREAD

**Issue by mehrikhan007** [mapbox/mapbox-android-demo#1276]
I have implemented the mapbox, user current location is successfully shown, camera tracks the user perfectly when user starts driving. A weird behavior is being observed when user drag the mapview or perform zoom in/out, camera tracking stops and never start again until the user restarts the activity.

Forgive me for any mistake, I'm writing here for the first time.

**Comment by LukasPaczos** [comment]
Hey @mehrikhan007, thanks for using Mapbox! Whenever the map is repositioned by the user, we won't restart the tracking automatically, you'll need to do it manually. Check out https://docs.mapbox.com/android/maps/overview/location-component/#cameramode for more info.

**Comment by mehrikhan007** [comment]
Hi @LukasPaczos, thanks for your response. i totally get it but as i mentioned i am a newbie and i have difficulty in understanding the link you have mentioned, can you please provide me with a small snippet of code about how can i achieve this or may be just redirect me to a link where i can see an example of how to get that task done. it will be appreciated.
Thanks

**Comment by LukasPaczos** [comment]
@mehrikhan007 here's an extensive demo that listens to `LocationComponent` camera and render mode changes and it also allows to change those modes on the fly https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationComponentCameraOptionsActivity.java.

**Comment by mehrikhan007** [comment]
@LukasPaczos thanks a bunch. I'll look into that and will get back to you soon.
