### ISSUE TITLE
Where is full Kotlin code of mapbox-android-demo ?

### ISSUE THREAD

**Issue by manishpatelgt** [mapbox/mapbox-android-demo#1277]
I don't find full Kotlin support code for **mapbox-android-demo**

How do i get for reference ?

**Comment by langsmith** [comment]
The demo app has several Kotlin examples, but there's no **full** Kotlin version of the app.

If there's an example that you want in Kotlin, you can use Android Studio's auto-convert feature to get started. 

- https://developer.android.com/kotlin/add-kotlin#convert
- https://www.jetbrains.com/help/idea/mixing-java-and-kotlin-in-one-project.html
- https://nilsmagnus.github.io/post/android-annotations-kotlin/
