### ISSUE TITLE
Failed to load source composite:403

### ISSUE THREAD

**Issue by pglve** [mapbox/mapbox-android-demo#1279]
network normal but map not display:
[HTTP] Request with response = 403: Forbidden
ager}[Style]: Failed to load source composite: HTTP status code 403
[HTTP] Request with response = 304: Not Modified

**Comment by tobrun** [comment]
http code 403 means Forbidden. I'm guessing your aren't including an access token?

**Comment by pglve** [comment]
has already set token:
     Mapbox.getInstance(this, "sk.*******************");

**Comment by langsmith** [comment]
Does it work if you use your Mapbox account's `Default public token`  found in https://account.mapbox.com/access-tokens? It starts with `pk.` rather than `sk.`

Where is this crash happening in the app? Which example are you trying to load?

**Comment by langsmith** [comment]
Closing this because I haven't heard back. More than happy to reopen this ticket and continue the conversation if I hear back.
