### ISSUE TITLE
how to add location searches with offline maps?

### ISSUE THREAD

**Issue by AchmadFadillah** [mapbox/mapbox-android-demo#1281]
I want to make an offline map that can search for locations offline whether it can? and how solution.
Thank you..

**Comment by langsmith** [comment]
Hey @AchmadFadillah , thanks for looking into Mapbox. For Mapbox implementation questions, please contact our excellent support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231. They'll be able to help you!
