### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by trgan96** [mapbox/mapbox-android-demo#1283]
I think Mapbox should support ripple effect for marker or layer intead of design ^^

**Comment by langsmith** [comment]
Hi @trgan96 , can you say more about this "ripple effect"? What do you mean? Is there an online example that you can point to?

**Comment by trgan96** [comment]
https://user-images.githubusercontent.com/49856744/71782189-fdda4300-3009-11ea-9993-ba422fc58add.png

**Comment by trgan96** [comment]
https://github.com/aarsy/GoogleMapsAnimations

**Comment by trgan96** [comment]
https://drive.google.com/drive/folders/1wzgjEF4ZXbL8LGK08a6vu9UMzUt8gpbh?usp=sharing
