### ISSUE TITLE
Confusing misuse of lat/lng

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-android-demo#1284]
A lot of times Mapbox compontents require lattitude and logitude as parameters, but **longitude as the first one**. But there are other Mapbox components which require **latitude as first** parameter. This is very confusing and easy to produce errors with it. The default should be `component(latitude, longitude);`

**Comment by langsmith** [comment]
Yes, this variance across Mapbox tools is known and mentioned at https://docs.mapbox.com/help/glossary/lat-lon/ . See https://github.com/nitaliano/react-native-mapbox-gl/issues/188#issuecomment-165676394 too.

It is varied across the geospatial industry as well: https://macwright.org/lonlat/

Closing as there's nothing actionable here and not an actual problem with the demo app.
