### ISSUE TITLE
E/UncaughtException: java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded.

### ISSUE THREAD

**Issue by rajiniyadav** [mapbox/mapbox-android-demo#1294]
Getting below issue..if i try to use mapview on second activity
E/UncaughtException: java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded.

**Comment by langsmith** [comment]
>Getting below issue..if i try to use mapview on second activity

I'm not sure what you mean by this. Can you provide more information about what you're trying to achieve?

**Comment by langsmith** [comment]
The fix is probably 

```java
mapboxMap.getStyle(new Style.OnStyleLoaded() {
              @Override
              public void onStyleLoaded(@NonNull Style style) {


              }
            });
```

Then use the `style` object returned by `onStyleLoaded()` to get the source that you want. `style.getSourceAs("source-id");`
