### ISSUE TITLE
Unable to Set custom marker 

### ISSUE THREAD

**Issue by Ajayrajan7** [mapbox/mapbox-android-demo#1299]
I'm using mapbox-sdk:6.0.1 and i want to display some custom markers in the map. But i cant set the markers on the map. 
This is the code that i'm using to add marker.
`       MarkerOptions options= new MarkerOptions();
        options.title("pos");
        IconFactory iconFactory=IconFactory.getInstance(MainActivity.this);
        Icon icon=iconFactory.fromResource(R.drawable.home);
        options.icon(icon);
        options.position(new LatLng(80.27,13.09));`
Any idea to solve this issue??

**Comment by langsmith** [comment]
hey @Ajayrajan7 , thanks for using Mapbox. Tickets in this repo are for issues with the demo app specifically. If you've got Mapbox implementation questions, please contact our great Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231.
