### ISSUE TITLE
User's location slow response when closed system GPS

### ISSUE THREAD

**Issue by Hugo-Hyenatek** [mapbox/mapbox-android-demo#1313]
Phone: Google Pixel 4, Android 10
Mapbox Demo app from google play download.

User's location response 25~40 Interval in seconds when GPS close.

[Demo Video](https://drive.google.com/file/d/1CeZTCNf_gH9LEAeAr6KIDHgjsrrgO7i3/view?usp=sharing)

**Comment by langsmith** [comment]
Hey @Hugo-Hyenatek , thanks for the ticket. This isn't an issue with the demo app specifically. In the end, the Maps SDK's `LocationComponent` is based on https://github.com/mapbox/mapbox-events-android. I don't think the timing after closing GPS is an issue with https://github.com/mapbox/mapbox-events-android, but if you'd like to continue the conversation, please open a ticket at https://github.com/mapbox/mapbox-events-android/issues.

cc @harvsu @nkukday
