### ISSUE TITLE
GeoJson

### ISSUE THREAD

**Issue by zhongzhibin617** [mapbox/mapbox-android-demo#1315]
Please help me.
Using Android SDK There is a question

http://xxx/data/v3/{z}/{x}/{y}.geojson

How to use
I didn't find the answer in the demo
please

**Comment by langsmith** [comment]
Seems that you're asking how to use GeoJSON that's hosted at a URL. If so, see the following examples, which show how to create a `GeoJsonSource` with a hosted GeoJSON link. `new URI` is the key.

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeojsonLayerInStackActivity.java#L53

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CreateHotspotsActivity.java#L72
