### ISSUE TITLE
Release 4.2.0-beta.2

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#132]
Issue to track next demo app release adding a handful of new examples, cleaning up code, and using the 4.2.0-beta.2 version of SDK released earlier today:

- [x] Update gradle dependencies
- [x] Finish cleaning up code
- [x] Add OffRoute example to MAS section
- [x] Build release APK

cc: @zugaldia

**Comment by cammace** [comment]
Published to Play store, should show up in a few hours.

**Comment by zugaldia** [comment]
@cammace 🎉
