### ISSUE TITLE
Turf inside/within example

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#134]
Make an example showing off the [Turf inside](https://github.com/mapbox/mapbox-java/blob/master/libandroid/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfInsideActivity.java) functionality similar to this example: https://www.mapbox.com/analysis-demos/nyc-attractions/#12.41/40.7184/-74.0198

**Comment by langsmith** [comment]
[Turf Inside example has been created and added to the demo app](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/mas/TurfInsideActivity.java)
