### ISSUE TITLE
Indoor Map

### ISSUE THREAD

**Issue by fatima-z** [mapbox/mapbox-android-demo#1343]
Hello, 
The IndoorMap is not working for me, it runs for few seconds and then the app stops.

**Comment by fatima-z** [comment]
import com.mapbox.mapboxandroiddemo.R;

I don't know how I change this import, cause I just have the two file (activity and layout) for indoorMap

**Comment by langsmith** [comment]
Thanks for checking out the app @fatima-z 

> The IndoorMap is not working for me, it runs for few seconds and then the app stops.

Does it crash? Nothing shows up? 

>I don't know how I change this import, cause I just have the two file (activity and layout) for indoorMap because after I change the package this import is deleted

Try deleting `import com.mapbox.mapboxandroiddemo.R;` from the import list at the top of the activity file and then import the `R` file that's specific to your project.

**Comment by fatima-z** [comment]
It works, thank you !
