### ISSUE TITLE
Add WMS demo

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-android-demo#145]
With the introduction of the Runtime Style API we can now load a WMS source (and [other templated URLs](https://www.mapbox.com/mapbox-gl-style-spec/#sources)) using the `tiles` parameter of a `raster` source. The corresponding JS example is in https://www.mapbox.com/mapbox-gl-js/example/wms/.

Let's bring this same example to Android as this is to some extend the equivalent to Google Maps' `UrlTileProvider` and can be useful to others migrating from that approach.

/cc: @cammace @ivovandongen @sean-heff

**Comment by 1ec5** [comment]
I think there should be two different demos, one using WMS and one using the standard `{x}`, `{y}`, `{z}` tokens. WMS is very interesting to GIS folks but not as interesting to other developers.

**Comment by zugaldia** [comment]
@1ec5 Do you know if there there is a equivalent GL JS demo using the standard {x}, {y}, {z} tokens that we could replicate here?

**Comment by 1ec5** [comment]
No, but now we can implement [this Android SDK example](https://www.mapbox.com/android-sdk/examples/custom-raster/) with a non-Mapbox-hosted tile set without having to publish a separate raster-v8.json style anywhere.

**Comment by cammace** [comment]
Examples now merged, here's what it looks like (minus the toolbar and status bar):

![](http://i.imgur.com/k14WdRG.png)

**Comment by zugaldia** [comment]
@cammace 👍 Fantastic.

@1ec5 Yeah, I can see that as an option for the custom raster style example. Could you please ticket that separately? Thanks!
