### ISSUE TITLE
Add show user location to wearable module

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#158]
Transfer the [user location example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/BasicUserLocation.java) to wearable module. 

cc: @zugaldia

**Comment by langsmith** [comment]
Closing because [Pablo added this to demo app](https://github.com/mapbox/mapbox-android-demo/pull/255)
