### ISSUE TITLE
Introduce additional map styles besides default to some examples

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#163]
Right now each examples using one of the 5 default styles found in the SDK. It would be great to start using various styles created by others in this app to show off custom studio styles. What do you think @zugaldia?

**Comment by zugaldia** [comment]
@cammace How about picking a few from https://www.mapbox.com/gallery? cc: @tatsvc

**Comment by tatsvc** [comment]
@zugaldia @cammace that's definitely an option! 

Maybe we should start with the ones made by Mapbox employees? 
You can grab map ids and tokens here: https://github.com/mapbox/www.mapbox.com/blob/mb-pages/gallery/index.html#L11-L297

**Comment by langsmith** [comment]
The link above is dead and I'm not really sure where I might find it these days in the Mapbox Github. 

My guess is that [mapbox.com/gallery](mapbox.com/gallery) isn't live anymore [as it seems to be in the legacy folder](https://github.com/mapbox/www.mapbox.com/blob/73122769bea4996a364c917df5464eedd052e7e2/legacy/gallery/index.html)

Is there a way to find the ids for the gallery's maps? @davidtheclark?  I'd love to use [@amyleew vintage one](https://www.mapbox.com/gallery/#map-7) somewhere in the Android demo app in particular!

**Comment by langsmith** [comment]
https://github.com/mapbox/www.mapbox.com/blob/mb-pages/gallery/index.html#L11-L297

**Comment by amyleew** [comment]
@langsmith - I've got the files on a repo https://github.com/mapbox/mapbox-gl-vintage-style enjoy!

**Comment by langsmith** [comment]
Thank you @amyleew 

Are the blueprint, roy lichtenstein, and/or swiss ski styles in repos? 😬 No worries if not. Give a mouse a cookie...

**Comment by cammace** [comment]
I've been collecting some map styles published by the carto team. Lets find a place for these styles in the demo app and then close this ticket but actively keep looking to add more and more custom styles.

Whaam! `mapbox://styles/cammace/cj5crfmjk0dmq2rmpg0fc8l7l`
Standard `mapbox://styles/cammace/cj53aeuj805f42rqbe6v94rgm`
moonlight: `mapbox://styles/cammace/cj3naq66b000i2rpjao5j5smu`

**Comment by langsmith** [comment]
Whaam!, Standard, and Moonlight are all now in the demo app.
