### ISSUE TITLE
Local style source file example

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#165]
Now that https://github.com/mapbox/mapbox-gl-native/pull/6497 it makes it possible to store the style JSON file locally.

cc: @zugaldia

**Comment by cammace** [comment]
Similar to https://github.com/mapbox/mapbox-android-demo/issues/163, let's just find an existing style and load the map style into the example from a local json file.

**Comment by zugaldia** [comment]
Would it make sense for this example to take advantage of https://github.com/mapbox/mapbox-plugins-android/pull/38 too?

**Comment by langsmith** [comment]
Fyi @cammace , I'm planning to use `Wham!` in this example which will mean that we have `Wham!`, `Standard`, and `Moonlight` in the demo app and can close #163
