### ISSUE TITLE
programmatically zoom out problem 

### ISSUE THREAD

**Issue by arpit999bicubic** [mapbox/mapbox-android-demo#187]
i am developing game. so i put all markers in map using json data. There is zoom in-out functionality in my game so when user click zoom in(programmatically) it's perfectly work with showing all markers.

but when user click zoom out then **all markers are gone**. Then i drag map suddenly shows the all  markers.   

i am using same button for zoom in-out.

Here is my code.

**adding marker using this method**

```
  public void addMarker(String title, int resource_id, LatLng latLng) {

        // Create an Icon object for the marker to use
        IconFactory iconFactory = IconFactory.getInstance(StartTourActivity.this);
        Drawable drawable = ContextCompat.getDrawable(StartTourActivity.this, resource_id);
        Icon icon = iconFactory.fromDrawable(drawable);

        // Add the custom icon marker to the map
        markerView =  map.addMarker(new MarkerViewOptions()
                .position(latLng)
                .title(title)
                .icon(icon));

    }
```

In my zoom button click listener

  ```
if (locationServices != null) {

                    switch (zoom) {

                        case 16:

                            zoom = zoom + 2;
                            map.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(locationServices.getLastLocation()), zoom));
                            bt_zoom.setBackgroundResource(R.mipmap.zoom_out);

                            break;
                        case 18:
                            zoom = zoom - 2;
                            map.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(locationServices.getLastLocation()), zoom));
                            bt_zoom.setBackgroundResource(R.mipmap.zoom_in);

                            break;
                    }


                } else {
                    MyApplication.okMessageDialog(StartTourActivity.this, "Gincana", "Location not found");
                }
```

**Comment by cammace** [comment]
Sounds like a bug we had in `4.2.0-beta.5`, update to `4.2.0` final build and see if that resolves the issue.

**Comment by arpit999bicubic** [comment]
getting this error after change to 4.2.0 

`Error:Module 'com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0' depends on one or more Android Libraries but is a jar`

**Comment by cammace** [comment]
are you also using Mapbox Java? You might need to also include `exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-java-services'` like found in this projects [`build.gradle`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/build.gradle#L51) file.

**Comment by cammace** [comment]
Stale issue, closing.
