### ISSUE TITLE
Android Things module

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#188]
We should create a module with some demos using the new Android Things SDK.

cc: @zugaldia

**Comment by zugaldia** [comment]
For now, I'm tinkering and putting some code in https://github.com/zugaldia/mapbox-things.

**Comment by langsmith** [comment]
Any progress on this @zugaldia ? Now possible to put any tinkering code in the demo app or no?

**Comment by zugaldia** [comment]
> Hardware graphics acceleration (OpenGL) is not currently enabled. APIs dependent on this functionality (such as WebView) are not available.

Let's close in favor of https://github.com/mapbox/mapbox-things. [GL is currently not supported](https://developer.android.com/things/preview/releases.html) and makes this unactionable for now.

**Comment by langsmith** [comment]
👍

**Comment by J3Patel** [comment]
@zugaldia I have tested https://github.com/JimSeker/opengl on android things. I think GL is supported ? I am trying to run mapBox on Things, normal mapview is working fine on it but navigation-ui is not working yet. let me know if you have more info on this.

**Comment by J3Patel** [comment]
@zugaldia I got it working on Android Thing raspberry pi.
we have to use minimum layers on map so I created custom map with 3 layers.
can I commit working example of that here?
