### ISSUE TITLE
Up navigation is not working

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-android-demo#203]
Back button in ActionBar is not working in any activity.

**Comment by cammace** [comment]
Discussed internally, and the issue has been resolved

**Comment by Guardiola31337** [comment]
Still not working ¯\_(ツ)_/¯

**Comment by langsmith** [comment]
Besides in the language switch activity, it's not working for me either.

**Comment by cammace** [comment]
In the manifest, `.MainActivity` wasn't giving the correct path. Providing the full filepath fixes the issue.

```
 getParentActivityIntent: bad parentActivityName 'com.mapbox.mapboxandroiddemo.debug.MainActivity' in manifest
```

https://github.com/mapbox/mapbox-android-demo/pull/225 fixes this issue.
