### ISSUE TITLE
Weird track user location activity 

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#210]
The camera is zoomed and tilted way too much during the onCreate() of this activity

**Comment by cammace** [comment]
I think this is related to a Focal point issue, https://github.com/mapbox/mapbox-gl-native/issues/7940.

**Comment by tobrun** [comment]
zooming and tilting are unrelated to focalpoint?

**Comment by zugaldia** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/7940 was closed with 5.0.0, is this issue still happening?

**Comment by langsmith** [comment]
No longer an issue. Working fine for me with 5.0.2
