### ISSUE TITLE
Marker doesn't animate to new location if it's off screen 

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#216]
This is in AnimatedMarkerActivity.

If you drag the map so that the marker isn't visible on screen and then click somewhere on the map, the marker doesn't animate to that new location. Then, the marker re-appears at that last location that you clicked on once you zoom out a little bit.

![ezgif com-resize 2](https://cloud.githubusercontent.com/assets/4394910/22845528/fe8ecc9a-efb0-11e6-8423-4d367dbc5dc8.gif)

**Comment by tobrun** [comment]
@cammace retested with latest snapshot and this issue seems to been resolved with https://github.com/mapbox/mapbox-gl-native/pull/8064.
