### ISSUE TITLE
Add traffic to existing style example

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#223]
Currently we only have a style which includes the traffic tileset. We should create an example which shows how to make use of this tileset to display traffic on a users custom style using runtime. Note that this example should wait till https://github.com/mapbox/mapbox-gl-native/issues/7285 is resolved so we show to proper way of how to do this.

**Comment by zugaldia** [comment]
We should use the upcoming traffic plugin in https://github.com/mapbox/mapbox-plugins-android for this example.
