### ISSUE TITLE
Add localizations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#226]
When the upstream integration of multi language support in https://github.com/mapbox/mapbox-gl-native/issues/8155, we should update this codebase to support the same languages as added there. Additionally we can also update the store listing to reflect support of these languages.

**Comment by langsmith** [comment]
http://jeremie-martinez.com/2017/03/13/i18n-good-practices/

**Comment by langsmith** [comment]
@tobrun , do you need to first start a new project in Transifex for this?  How can I help with adjusting code?

**Comment by langsmith** [comment]
?

**Comment by tobrun** [comment]
@langsmith I added you as project maintainer, you should have the same user rights as me. Related on the topic of adding language support for mapbox-demo. I wasn't really handling this as a high priority but on the other hand this isn't a big lift.

cc @zugaldia

**Comment by langsmith** [comment]
ok, thanks. I'll look into things for the demo

**Comment by langsmith** [comment]
@tobrun , I was trying to start a new project in our account, but [only organization maintainers can create new projects](https://docs.transifex.com/projects/creating-a-project)

Are you a maintainer?

**Comment by tobrun** [comment]
cc @1ec5

**Comment by 1ec5** [comment]
[All set](https://www.transifex.com/mapbox/mapbox-android-demo/dashboard/). For expediency, I imported all the mapbox-gl-native project’s translation teams. Now you need to import the resources and set up autoupdating.

**Comment by langsmith** [comment]
![giphy](https://cloud.githubusercontent.com/assets/4394910/24926674/50b2b020-1eb1-11e7-9213-f3eb032fa421.gif)

**Comment by 1ec5** [comment]
Once some translations of strings.xml come in, we’ll want to [configure the `tx` client](https://docs.transifex.com/client/client-configuration/) so that we can run `tx pull -a` at any time to fetch new translations and check them into this repository.

It’s also possible to have Transifex autodetect new strings in strings.xml as they land in master, but that feature seems to misbehave with the Android XML format: mapbox/mapbox-gl-native#8641.

**Comment by zugaldia** [comment]
> Once some translations of strings.xml come in, we’ll want to configure the tx client so that we can run tx pull -a at any time to fetch new translations and check them into this repository.

We should add this as part of the release checklist.

**Comment by zugaldia** [comment]
Forgot to link the wiki page: https://github.com/mapbox/mapbox-android-demo/wiki/Release-process.

**Comment by langsmith** [comment]
I added that line to the wiki

**Comment by zugaldia** [comment]
@langsmith Thank you.

Is there any other actions left in this ticket? Or are we waiting for https://github.com/mapbox/mapbox-gl-native/issues/8155 to land?

**Comment by 1ec5** [comment]
`tx pull -a` won’t have the desired effect until we [configure this repository](https://docs.transifex.com/client/client-configuration/) for that tool, including specifying the destination and file format of each resource in Transifex.

**Comment by 1ec5** [comment]
Catalan is complete.
