### ISSUE TITLE
Create Demo Of Offline Map Capabilities

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-android-demo#23]
Offline Map Functionality is available as of `0.5.1`.  Create an example to showcase it working in the Demo App similar to the [Test App](https://github.com/mapbox/mapbox-android-sdk/blob/mb-pages/MapboxAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/android/testapp/SaveMapOfflineTestFragment.java).

**Comment by cammace** [comment]
This is an ancient ticket and we now have offline examples using the new SDK, closing!
