### ISSUE TITLE
Add support for Analytics

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-android-demo#232]
We currently use Firebase for crash reporting, but not for analytics. Let's add support for analytics too to have a better idea of usage/devices. 

cc: @langsmith

**Comment by langsmith** [comment]
[/r/androiddev thread about using Firebase analytics in an open source app](https://www.reddit.com/r/androiddev/comments/5k9vyp/using_analytics_in_an_open_source_app/)

**Comment by langsmith** [comment]
Analytics conversation has moved to https://github.com/mapbox/gl-internal/issues/646

**Comment by langsmith** [comment]
Being addressed by [this branch/pr](https://github.com/mapbox/mapbox-android-demo/pull/306)

**Comment by langsmith** [comment]
Fixed by https://github.com/mapbox/mapbox-android-demo/pull/336
