### ISSUE TITLE
Wrong screen position for pulsing user position.

### ISSUE THREAD

**Issue by CYBOPOB** [mapbox/mapbox-android-demo#241]
I've implemented pulsing user position as 
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/AnimatedLocationIconActivity.java

It works correctly but have two bugs.
1 Position on screen is wrong. 
Real position is Madrid.
![madrid](https://cloud.githubusercontent.com/assets/1652776/24099697/5b809e98-0d79-11e7-8fde-41d1b05c031b.png)
Usual marker works like a charm.
But it seems when mapbox display pulsing user position it uses left top corner of image instead of it center.

**Comment by langsmith** [comment]
Hi @CYBOPOB ,

What version of our Maps SDK are you using? 5.0.2 is our latest version. If you're not using 5.0.2, please try updating your project via [these instructions](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update), try the example again, and let me know if the same bugs appear. Thanks!

**Comment by cammace** [comment]
You are right @CYBOPOB. in PR #299 I have fixed this issue by adding `.anchor(0.5f, 0.5f),` to the marker view.
