### ISSUE TITLE
MainActivity OnClick crash

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#243]
Stacktrace:
```java
com.mapbox.mapboxandroiddemo.MainActivity$1.a ()
com.mapbox.mapboxandroiddemo.c.a$1.onClick ()
android.view.View.performClick (View.java:4909)
android.view.View$PerformClick.run (View.java:20390)
android.os.Handler.handleCallback (Handler.java:815)
android.os.Handler.dispatchMessage (Handler.java:104)
android.os.Looper.loop (Looper.java:194)
android.app.ActivityThread.main (ActivityThread.java:5798)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1109)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:875)

```

[Mapping file](https://gist.github.com/tobrun/39e0582ad329f57e8cdbc61dbdf0f5c9)

**Comment by JennyVayla** [comment]
Tried reproducing it, but couldn't do it. Can I have more details on it?

**Comment by tobrun** [comment]
This crash came from Firebase, don't have additional details either. Looked at the code in [MainActivity](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java) related to onClick and they are either no-op or platform code. Not actionable for now, thanks for looking though. Closing.
