### ISSUE TITLE
Draggable marker

### ISSUE THREAD

**Issue by gmribas** [mapbox/mapbox-android-demo#251]
Is there a way to make a marker draggable?
I've found this [workaround](http://stackoverflow.com/questions/26793732/mapbox-android-sdk-draggable-marker) but it doesn't work.

**Comment by langsmith** [comment]
Hi @gmribas,

We're aware of this potential product feature and [already have a ticket open in the Mapbox GL Native repo regarding draggable markers](https://github.com/mapbox/mapbox-gl-native/issues/2450).

**Comment by gmribas** [comment]
Thanks @langsmith
