### ISSUE TITLE
Unidentified crash in libc while navigating the map

### ISSUE THREAD

**Issue by JonasVautherin** [mapbox/mapbox-android-demo#26]
On some devices, the App crashes when navigating the Map. I observe the same in my own App using the Android SDK.

    Build fingerprint: 'samsung/sltexx/slte:4.4.4/KTU84P/G850FXXU2BNK3:user/release-keys'
    Revision: '10'
    pid: 14515, tid: 14553, name: downloader  >>> com.mapbox.mapboxandroiddemo <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
    Abort message: 'invalid address or address of corrupt block 0x6f430d70 passed to dlfree'

I copied the full message here:
http://pastebin.com/ZeZQ30Js

**Comment by bleege** [comment]
Thanks for the feedback @JonasVautherin.  Sorry that this his happening to you.  Can you tell us more about which Samsung device your seeing this on?

**Comment by JonasVautherin** [comment]
This one happened on a Samsung Galaxy Alpha. In my own App, I could reproduce it on a Galaxy S4 (with Cyanogenmod 11) and Galaxy S5.

**Comment by bleege** [comment]
@JonasVautherin I just released 1.7.3 of the Demo App on Google Play with the new `0.7.3` SDK release.  Thanks again for all your help!
