### ISSUE TITLE
Add icons to nav drawer sections

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#273]
Might be nice to add appropriate [Material Design icons](https://material.io/icons/) (or some sort of custom Mapbox ones _**if**_ we already have them) to the left of the nav drawer sections.

cc @cammace @mayagao  

![screen shot 2017-04-10 at 2 22 14 pm](https://cloud.githubusercontent.com/assets/4394910/24883288/2375c236-1df9-11e7-9cd9-14cf3dff24ce.png)

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-android-demo/pull/274 adds this, closing.
