### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-android-demo#275]
This repository needs a license file. In terms of choosing a license, a permissive license would allow the example code to be used and adapted more widely, which is consistent with the purpose of this repository.

/cc @mapbox/android

**Comment by zugaldia** [comment]
@1ec5 Good catch. Let's use the 2-clause BSD license that we use in https://github.com/mapbox/mapbox-gl-native/blob/master/LICENSE.md.

**Comment by langsmith** [comment]
Resolved with https://github.com/mapbox/mapbox-android-demo/pull/278
