### ISSUE TITLE
Update demo app version on China app stores?

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#279]
http://android.app.qq.com/myapp/detail.htm?apkName=com.mapbox.mapboxandroiddemo

http://zhushou.360.cn/detail/index/soft_id/2114257?recrefer=SE_D_Mapbox

It seems that we have pretty outdated versions of the demo app on Chinese app stores.

Once we/I finish [multi-language support for the demo app](https://github.com/mapbox/mapbox-android-demo/issues/226), maybe we can think about updating the Chinese app stores?

I would think that a beautiful up-to-date app with lots of examples in Simplified/Traditional, would be really great for @KarenZZhang 's marketing and dev relations work.

cc @cammace @LornTao @zugaldia

**Comment by KarenZZhang** [comment]
@langsmith Really love it! We can use it widely.

**Comment by langsmith** [comment]
I'm going to close this ticket. My feeling is that this is no longer a ticket related to the state of the demo app, but now more of a China marketing ticket. My understanding is that @Guardiola31337 [has done all of the necessary work](https://github.com/mapbox/gl-internal/issues/597) for @KarenZZhang / @LornTao to update the app's apk on the China stores whenever they'd like to.  [Setting up multi-language support](https://github.com/mapbox/mapbox-android-demo/issues/226)  shouldn't be a blocker for this. We only have 3% of the demo app's strings translated in to Chinese (简体) anyways.

@KarenZZhang , perhaps @Guardiola31337 can create another .apk when we do our 5.1.0 release in the Google Play Store. His build was about a month ago and there have been several improvements to the app since then. However, his build of the demo app will be a huge upgrade over the old version that's currently in [China stores]
(https://github.com/mapbox/china/issues/445#issuecomment-284316216). Don't forget to update the Mapbox logo 😉 

Please re-open the ticket if you object to my closing it...

**Comment by chriswu42** [comment]
Reopening this ticket since it appears that we have not uploaded the updated demo app.

@LornTao - Could you please comment here what else you will need to do this?

/cc @KarenZZhang 

Related: https://github.com/mapbox/gl-internal/issues/597

**Comment by LornTao** [comment]
@langsmith 
if you want me to update the demo app in the China stores, please provide me the account and password of each android app store, and the latest APK file. Thanks.

cc/ @KarenZZhang @chriswu42 @zugaldia

**Comment by KarenZZhang** [comment]
@LornTao Why you can't apply for the app store acccount by yourself? What file do you need that i can help? 

cc/@xinnong @chriswu42 @zugaldia

**Comment by KarenZZhang** [comment]
@zugaldia in US team, normally who are responsible for opening app store accounts?

**Comment by LornTao** [comment]
@langsmith 
Could you upgrade the latest version of the demo app to [here](http://android.app.qq.com/myapp/detail.htm?apkName=com.mapbox.mapboxandroiddemo) with your account like you uploaded the apk to the china stores last time. thank you!
cc/@xinnong @chriswu42 @zugaldia

**Comment by langsmith** [comment]
Ok @LornTao . I thought that the China team did past uploading and that you all would have the account info . Can you give me a final list of the stores that you want me to upload/update?

@zugaldia / @cammace , do we have any login info for the China stores?  I don't see anything in Meldium.

@KarenZZhang , once I find the China store account info, I'll put it in Meldium. That way, you can sign in and add app description info (应用信息) if you ever want to.

**Comment by zugaldia** [comment]
This is a duplicate conversation, closing here.
