### ISSUE TITLE
strings.xml should mark more strings as untranslatable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-android-demo#280]
[strings.xml](https://github.com/mapbox/mapbox-android-demo/blob/7f2dfe503d000908fed50b1158942603d58907c8/MapboxAndroidDemo/src/main/res/values/strings.xml) has a whopping 194 strings, many of which are URLs to screenshots. While it’s true that some of these screenshots include translatable strings, I don’t think they’re a good use of translator time. We should mark them as untranslatable.

/ref #226
/cc @langsmith @tobrun

**Comment by langsmith** [comment]
Closing this because the PR above fixed it.

**Comment by 1ec5** [comment]
The strings remain translatable at Transifex. Be sure to reimport the source file to update Transifex. (Alternatively, enable autoupdating, but beware mapbox/mapbox-gl-native#8641.)

**Comment by langsmith** [comment]
Uploaded the strings resource file (with `translatable="false"` in the appropriate places) into Transifex
