### ISSUE TITLE
Update DC Mapbox address on Play Store

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#284]
![screen shot 2017-04-17 at 5 14 05 pm](https://cloud.githubusercontent.com/assets/4394910/25109439/57bee750-2391-11e7-9895-7d1d3e4d5237.png)

**Comment by cammace** [comment]
paging @zugaldia for this one, I tried logging into apps account but got hit by 2 factor authentication. Need to be the account owner to change this 😞 

![screen shot 2017-04-25 at 5 00 47 pm](https://cloud.githubusercontent.com/assets/5652865/25407671/385040fa-29d9-11e7-9eb7-a298de62b248.png)

**Comment by zugaldia** [comment]
@cammace Sorry about that. I just updated it.
