### ISSUE TITLE
package com.mapbox.services.api.navigation.v5 does not exist

### ISSUE THREAD

**Issue by nanomb** [mapbox/mapbox-android-demo#285]
when compiling com.mapbox.mapboxandroiddemo I get these errors:

    D:\\Android\samples\mapbox-android-demo-master\MapboxAndroidDemo\src\main\java\com\mapbox\mapboxandroiddemo\labs\OffRouteActivity.java
    Error:(35, 45) error: package com.mapbox.services.api.navigation.v5 does not exist
    Error:(71, 11) error: cannot find symbol class RouteUtils
    Error:(97, 26) error: cannot find symbol class RouteUtils
    Error:(186, 26) error: cannot find symbol class RouteUtils
    Error:(189, 26) error: cannot find symbol class RouteUtils
    Error:(192, 26) error: cannot find symbol class RouteUtils
    Error:(195, 26) error: cannot find symbol class RouteUtils
    Error:Execution failed for task ':MapboxAndroidDemo:compileGpservicesDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.

**Comment by zugaldia** [comment]
@nanomb Did this happen compiling the demo app using a SNAPSHOT version of `com.mapbox.mapboxsdk:mapbox-android-ui`? This is due to the Navigation SDK being extracted into [its own repository](github.com/mapbox/mapbox-navigation-android), that file was moved to a different package.
