### ISSUE TITLE
Use APK Splits

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#288]
One of the tips we give users when it comes to shrinking their apk size is leveraging [apk splits](https://developer.android.com/studio/build/configure-apk-splits.html#configure-abi-split). This results in building different apk's for all the different supported abi's in the application. Google play is optimised to only download the apk for the abi of the device you're installing it on. We currently don't do any regression testing around this feature. I feel mapbox demo would be a good candidate as it would significantly decrease the download size of the apk.

cc @mapbox/android

**Comment by tobrun** [comment]
This happened and we were able tot take of 10mb of the final app size (<20mb depending on ABI). We are now uploading 10 different apks to Google Play because of above + additional wear apks.

**Comment by zugaldia** [comment]
> we were able tot take of 10mb of the final app size (<20mb depending on ABI). 

@tobrun or @langsmith could you add a note about the numbers ^^^^ to https://github.com/mapbox/mapbox-gl-native/wiki/Strategies-to-reduce-Android-APK-size#sample-code when you have a chance?
