### ISSUE TITLE
Update application icon to match new Mapbox branding

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-android-demo#289]
Mapbox unveiled a new logo last week. This application’s icon should reflect that branding instead of using an “M”.

/cc @cammace @langsmith

**Comment by langsmith** [comment]
I thought we were going with @cammace 's ......


![f4090468-24f6-11e7-8450-3b8871f24091](https://cloud.githubusercontent.com/assets/4394910/25364481/be32c8c2-2917-11e7-8e9c-b11326767db0.png)

**Comment by 1ec5** [comment]
That looks great @langsmith. Can you swap out images such as https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/res/mipmap-hdpi/ic_launcher.png with this new artwork?

**Comment by langsmith** [comment]
Will do @1ec5 .

[I've updated/added colors to the Android demo app's color file](https://github.com/mapbox/mapbox-android-demo/pull/290), using the values from [the Mapbox style guide](https://www.mapbox.com/styleguide/colors/). Does anything need to happen with updating colors in any other repos?

**Comment by langsmith** [comment]
@1ec5 , 

https://github.com/mapbox/mapbox-android-demo/pull/292 by @cammace adds a new launcher icon

**Comment by cammace** [comment]
new icons been merged into master. Closing
