### ISSUE TITLE
Add class level javadoc 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#301]
To give users a bit more context when they are solely looking at the source code of an example (as with the new android-docs setup?). We could add a couple of lines in the class level JavaDoc. I would suggest  copying the description we currently show on mapbox.com (eg. `Use Mapbox GL clustering to visualize point data as a heatmap.`. 

cc @langsmith @cammace

**Comment by langsmith** [comment]
Fixed with #371
