### ISSUE TITLE
Add example for "clicking" a Layer

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#305]
Capturing from conversations with @Guardiola31337, it isn't that intuitive for a user to detect click events on a polygon that was added as a GeoJsonSource. 

![device-2017-04-27-095444](https://cloud.githubusercontent.com/assets/2151639/25474154/6faa89de-2b32-11e7-8100-a0a72c5d45f6.png)

Click events on the FillLayer can be detected with queryRenderedFeatures:

```java
  @Override
  public void onMapReady(@NonNull final MapboxMap map) {
    mapboxMap = map;
    try {
      source = new GeoJsonSource(ID_GEOJSON_SOURCE, new URL("https://gist.githubusercontent.com/tobrun/cf0d689c8187d42ebe62757f6d0cf137/raw/4d8ac3c8333f1517df9d303d58f20f4a1d8841e8/regions.geojson"));
      mapboxMap.addSource(source);
    } catch (MalformedURLException malformedUrlException) {
      Timber.e("Invalid URL", malformedUrlException);
    }

    layer = new FillLayer(ID_GEOJSON_LAYER, ID_GEOJSON_SOURCE);
    layer.setProperties(fillOpacity(0.5f));
    mapboxMap.addLayer(layer);

    mapboxMap.setOnMapClickListener(new MapboxMap.OnMapClickListener() {
      @Override
      public void onMapClick(@NonNull LatLng point) {
        PointF pointf = mapboxMap.getProjection().toScreenLocation(point);
        RectF rectF = new RectF(pointf.x-10, pointf.y-10, pointf.x+10, pointf.y+10);
        List<com.mapbox.services.commons.geojson.Feature> featureList = mapboxMap.queryRenderedFeatures(rectF, ID_GEOJSON_LAYER);
        for (com.mapbox.services.commons.geojson.Feature feature : featureList) {
          Timber.e("Feature found with %s", feature.toJson());
        }
      }
    });
```

The code above only logs when clicking the FillLayer.

**Comment by cammace** [comment]
We have an example which does something similar but with [symbol layers](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java#L98) and another example which uses turf inside instead to determine if a coordinate is inside the polygon or not.

**Comment by tobrun** [comment]
>  another example which uses turf inside instead to determine if a coordinate is inside the polygon or not

that example should be removed

**Comment by langsmith** [comment]
Added to demo app with #402

**Comment by caopeng000** [comment]
I have a question，How can I judge whether a latitude and longitude is in a geographical fence？Can reply as soon as possible！thanks
