### ISSUE TITLE
3d-extrusion Display buildings in 3D

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#315]
Match this GL-JS example https://www.mapbox.com/mapbox-gl-js/example/3d-buildings/

**Comment by langsmith** [comment]
I will work on this one first

**Comment by tobrun** [comment]
@langsmith code for this in https://github.com/mapbox/mapbox-gl-native/pull/8845/files

**Comment by langsmith** [comment]
Thanks
