### ISSUE TITLE
3d-extrusions Population density in 3D

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#319]
Show population density visually on a map in 3D https://www.mapbox.com/blog/population-inspector/

**Comment by langsmith** [comment]
I've started on this with the `ls-3d-population-density-example` branch and will continue working on this example...

![ezgif com-resize](https://cloud.githubusercontent.com/assets/4394910/25873814/c4a87e78-34c4-11e7-8c20-a3e495817846.gif)
