### ISSUE TITLE
Mapbox devpreview crashes on Sony Smartwatch 3 SWR150

### ISSUE THREAD

**Issue by sergiocasero** [mapbox/mapbox-android-demo#330]
Hello, just to inform that the demo app crash on my smartwatch. The crash occurs when I click on "Simple map view"

**Comment by langsmith** [comment]
Hi @sergiocasero ,

Thanks for bringing this to our attention. Would you be able to provide a copy of your log when the crash occurs? That would help give us more context around what might be going wrong.

Thanks

**Comment by Guardiola31337** [comment]
Hey @sergiocasero 👋 
A new version of the [demo app](https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo) was released on Google Play 🎉
Could you retest with the latest version? Thank you for the report!
