### ISSUE TITLE
Add Kotlin SDK examples

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-android-demo#337]
Now that [Google supports Kotlin on Android officially](https://android-developers.googleblog.com/2017/05/android-announces-support-for-kotlin.html) we should add a Kotlin version of the SDK examples.

**Comment by icochico** [comment]
I am working on exactly that, if it can be helpful I'd love to share the code!

**Comment by icochico** [comment]
Here is an example of the basic MapView all in Kotlin https://github.com/icochico/KotlinMapBox

**Comment by langsmith** [comment]
#860 adds a basic example of simple Kotlin `MapView`. We've also got several examples using Kotlin. The app now supports Kotlin examples. We're happy to accept other Kotlin prs from external developers too! Anyways, I think this "issue" is now resolved. We're not going to re-create every existing example into Kotlin, resulting to two versions of the same visual example. Rather, we'll use Kotlin to make a new example on an ad-hoc basis.
