### ISSUE TITLE
Add picture-in-picture support

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-android-demo#338]
Android O brings [picture-in-picture](https://developer.android.com/training/tv/playback/picture-in-picture.html) support for apps (link is from Android TV, can't find docs yet for regular Android). This a feature that let the user see the map "minimized" while they use other apps. Let's bring support for this to the demo app in preparation for the O launch.

![android-o-dev-preview-picture-in-picture](https://cloud.githubusercontent.com/assets/6964/26325081/7b5149a0-3f03-11e7-8199-54083ffc7b07.jpg)

cc: @langsmith

**Comment by langsmith** [comment]
[I've created a branch and set up example basics](https://github.com/mapbox/mapbox-android-demo/compare/ls-picture-in-picture?expand=1#diff-93b70afa10ac41c9639acecbd55d75e4). 

Still need to actually handle fab onClick for showing the pop up window, etc.

**Comment by langsmith** [comment]
[some more docs about picture-in-picture](https://developer.android.com/preview/api-overview.html#opip)

**Comment by langsmith** [comment]
Ok, I've got it working on an emulator that's running O 👇  I guess I'll make a pr and add it to the demo app once Android O is released?

![pictureinpicture](https://user-images.githubusercontent.com/4394910/28739125-1e5392a6-73ad-11e7-9190-083139ccc0ef.gif)

**Comment by langsmith** [comment]
Ok, I've got it working on an emulator that's running O 👇  I guess I'll make a pr and add it to the demo app once Android O is released to more devices? Or just go ahead and add now?

![pictureinpicture](https://user-images.githubusercontent.com/4394910/28739125-1e5392a6-73ad-11e7-9190-083139ccc0ef.gif)
