### ISSUE TITLE
Animation expand and contrain cluster styles

### ISSUE THREAD

**Issue by webserveis** [mapbox/mapbox-android-demo#342]
Sample Mapbox Javascript
https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/

Is posible add animation effect cluster layer in Android?

**Comment by langsmith** [comment]
Hi @webserveis , here's an example of data clusters on Android: https://www.mapbox.com/android-sdk/examples/create-style-clusters/

Thanks for using Mapbox!
