### ISSUE TITLE
Add Firebase performance monitoring

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#345]
At Google I/O this year, firebase performance monitoring tools were announced:

> It provides an SDK to capture and instrument performance metrics in production, and a console to gain insights about the data captured by the SDK. 

It pretty much boils down to adding one line of code to get a whole bunch of metrics. 

See the [startup guide](https://firebase.google.com/docs/perf-mon/get-started-android), this [clip](https://firebase.googleblog.com/2017/05/introducing-firebase-performance.html) or the related [blogpost](https://firebase.googleblog.com/2017/05/introducing-firebase-performance.html) for more information. 

cc @mapbox/android

**Comment by zugaldia** [comment]
> It pretty much boils down to adding one line of code to get a whole bunch of metrics.

With such a simple set up, I wonder if we could squeeze in this feature in the upcoming 5.1 milestone. @langsmith what do you think?
