### ISSUE TITLE
Add Mixpanel push notifications

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#349]
[Mixpanel Android push notifications](https://mixpanel.com/help/reference/android-push-notifications)

Add the ability for push notifications for helpful MarComm around new examples, features, updates, etc.

**Comment by langsmith** [comment]
@zugaldia , thoughts on dealing with push notifications in 🇨🇳 🇨🇳 🇨🇳 🇨🇳 ?

**Comment by langsmith** [comment]
@zugaldia  

I've opened a branch that has changes to the demo app for using Mixpanel. But Mixpanel notifications use GCM, so no dice in 🇨🇳 . 

Add code to check whether device is in China and if so, use a different service:[https://www.quora.com/What-are-some-alternative-push-notifications-for-Google-services-that-are-compatible-with-China-for-Android](https://www.quora.com/What-are-some-alternative-push-notifications-for-Google-services-that-are-compatible-with-China-for-Android)

**Comment by langsmith** [comment]
fyi, I had set everything up and tried to run the app for the first time, but 

```
compile "com.mixpanel.android:mixpanel-android:5.1.4"
    compile "com.google.android.gms:play-services:7.5.0+"
```
pushes the method count over 64k. I added `multiDexEnabled true` to the `debug` build type for the time being.

**Comment by zugaldia** [comment]
>  thoughts on dealing with push notifications in 🇨🇳?

@LornTao What's the preferred service push notifications that we could integrate into the demo app?

**Comment by langsmith** [comment]
Closing because I don't think we're ever going to use Mixpanel and/or push notifications. If we do add notifications, we'd probably just use Firebase.
