### ISSUE TITLE
Resolve the LocationSource.getLocationEngine(this) error

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#359]
@tobrun has merged [this PR](https://github.com/mapbox/mapbox-android-demo/pull/358/files) to the demo app. But there was a past Bitrise test that crashed because of several activities throwing the following line:
`error: cannot find symbol  locationEngine = LocationSource.getLocationEngine(this);`

I have yet to run tests now that Tobrun's pr was merged.

**Comment by zugaldia** [comment]
Thanks for the report @langsmith.

cc: @cammace @danesfeder as this might have affected navigation products as well.

**Comment by tobrun** [comment]
All of those issues were fixed [here](https://github.com/mapbox/mapbox-android-demo/commit/a65b12b377c49a6203689cd1b3b7c0c87c879667), closing.
