### ISSUE TITLE
Implement onSaveInstanceState

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-android-demo#38]
From @tobrun in https://github.com/mapbox/mapbox-gl-native/issues/2801#issuecomment-151518423

The app needs to forward `onSaveInstanceState` to avoid `null` where there should not be a `null`. Also without this implemented, rotating the device screen will lose the current map position.

**Comment by bleege** [comment]
It was missing `onStop()` too.

**Comment by bleege** [comment]
Good :eyes: @tobrun @ljbade !
