### ISSUE TITLE
onMarkerClick return 2 times when click at Marker

### ISSUE THREAD

**Issue by PhanVanLinh** [mapbox/mapbox-android-demo#387]
Here is my code for receive click at `MarkerView`
```
mMapBox.getMarkerViewManager().setOnMarkerViewClickListener(new MapboxMap.OnMarkerViewClickListener() {
    @Override
    public boolean onMarkerClick(@NonNull Marker marker, @NonNull View view,
            @NonNull MapboxMap.MarkerViewAdapter markerViewAdapter) {
        return true;
    }
});
```
But `onMarkerClick` always return 2 times whenever I click at a MarkerView. Why this happened and how can I solve it? Thank you
I see it notified fixed in here https://github.com/mapbox/mapbox-gl-native/issues/8309 from March but now it still happened. I am using 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar'

**Comment by cammace** [comment]
Could you update to 5.1.0 and see if the issue still exists. We are in the middle of fixing this issue and it might have gotten resolved. https://github.com/mapbox/mapbox-gl-native/issues/8159 is tracking this. In the future, any issues related to the Map SDK should go in that repo for a quicker response.
