### ISSUE TITLE
Add a example of rainfall data from radar into runtime styling.

### ISSUE THREAD

**Issue by LornTao** [mapbox/mapbox-android-demo#403]
@zugaldia 
There are no data-drive runtime styling example, add an example for showing the rainfall on our map.

cc/ @chriswu42 @xinnong @langsmith

**Comment by zugaldia** [comment]
@LornTao good idea - please open a PR with the proposed activity and make sure you tag @langsmith.

**Comment by LornTao** [comment]
update:
Because the offline data-- the radar data of rainfall is too large, so i will provide the PR after update the new geojson files.
