### ISSUE TITLE
Location layer plugin examples

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#408]
With the location layer plugin merged into master, we should prepare an example of usage. There's a few activities in the testapp that show how to use the plugin.

cc: @langsmith

**Comment by langsmith** [comment]
https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location

**Comment by langsmith** [comment]
Fixed by #411
