### ISSUE TITLE
Launcher icon needs to support adaptive icon

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#415]
Android O introduces [adaptive icons](https://developer.android.com/preview/features/adaptive-icons.html). The current icon being used seems to only support square shaped icon? Also, we still include the [old icon](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/res/mipmap-xxhdpi/ic_launcher.png) which needs to be removed.

**Comment by langsmith** [comment]
#418  removed the old icon. Still treating this ticket as a ticket for adaptive icon(s).

**Comment by langsmith** [comment]
cc  @YunjieLi   @emilyville

**Comment by YunjieLi** [comment]
Think sounds exciting! @langsmith @cammace . 

> In previous versions of Android, launcher icons were sized at 48 x 48 dp. You must now size your icon layers using the following guidelines:

> Both layers must be sized at 108 x 108 dp.
> The inner 72 x 72 dp of the icon appears within the masked viewport.
> The system reserves the outer 18 dp on each of the 4 sides to create interesting visual effects, such as parallax or pulsing.

It looks to me that we'll need to upload one foreground/icon image, and one background color (#273d56 in this case) for this, is that correct? Also is it safe to assume 72dp is 72px in png in this case? Happy to export the assets for you.

cc @emilyville

**Comment by langsmith** [comment]
<img width="1057" alt="screen shot 2017-07-31 at 10 30 33 am" src="https://user-images.githubusercontent.com/4394910/28789753-9395a808-75db-11e7-8626-bdf50f7a99b9.png">

Thanks @YunjieLi . The `#273d56` color looks great for the background color ☝️  If you can export and send me the white mapbox "logo" part (transparent background?) for the foreground layer, that'd be great. You can go ahead and send me a 72px one and Android Studio will handle resizing.
