### ISSUE TITLE
Add shrinkResources to build.gradle file

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#431]
Since we are using ProGuard for releasing, we should also include [`shrinkResources true`](https://developer.android.com/studio/build/shrink-code.html).

cc: @langsmith

**Comment by tobrun** [comment]
having `minifyEnabled true` automatically sets the flag for shrinkResources to true. 
No action needed on this issue. Closing,

**Comment by tobrun** [comment]
I was wrong, reopening
