### ISSUE TITLE
Unable to add locationLayer

### ISSUE THREAD

**Issue by rain89146** [mapbox/mapbox-android-demo#443]
When the application runs, the keep showing unable to find LifecycleObserver.

**Comment by langsmith** [comment]
Hi @rain89146 , when does this crash happen? When you open a particular example?

Thank you

**Comment by rain89146** [comment]
Thanks for the respond, i was trying to practice the example shown on the mapbox about adding LocationLayer. First issue was it couldn't compile the plugin, so i add "@aar" at the end of plugin address in the gradle, and it solved it. 
like this: compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.1.0@aar'

Then i did everything exactly like the example, and it ran into the LifecycleObserver issue:
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java
Error:(104, 27) error: cannot access LifecycleObserver
class file for android.arch.lifecycle.LifecycleObserver not found

**Comment by langsmith** [comment]
what does your entire Gradle file look like? It might be an issue with the version #s of other libraries that you've got...

**Comment by langsmith** [comment]
@rain89146 , closing, because I haven't heard back in a month and this is (potentially) an issue with the plugin more than the demo app itself. Please re-open if you'd like to continue the conversation. Thank you!
