### ISSUE TITLE
LocalStyleSourceActivity fails to load custom remote style

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-android-demo#448]
`LocalStyleSourceActivity` is trying to load a custom raster style from https://www.mapbox.com/android-docs/files/mapbox-raster-v8.json, but that's a 404 (probably a result of the recent docs migration). We need to either put the file there, or update the link.

cc: @langsmith

**Comment by langsmith** [comment]
@davidtheclark [fixed the file structure in `android-docs`](https://github.com/mapbox/android-docs/pull/189#pullrequestreview-55849245) and the example is now back to working as normal

**Comment by zugaldia** [comment]
Thank you @davidtheclark @langsmith for the quick fix!
