### ISSUE TITLE
How to animate a line from start to stop from GeoJsonSource

### ISSUE THREAD

**Issue by viettanbkdn** [mapbox/mapbox-android-demo#457]
I'm drawing a list of line on Mapbox using LineLayer from GeoJson file:
```
    try { 
        GeoJsonSource geoJsonSource = new GeoJsonSource("source", loadJsonFromRaw());
        mapboxMap.addSource(geoJsonSource);
 
        LineLayer lineLayer = new LineLayer("line-layer", "source");
        lineLayer.setProperties(
                PropertyFactory.lineWidth(1f), 
                PropertyFactory.lineColor(Color.RED)
        ); 
 
        mapboxMap.addLayer(lineLayer);
    } catch (IOException e) {
        e.printStackTrace();
    } 
```

Everything is ok, the lines could be drawn. But now, I want to animate the lines from start point to end point of each line when MapBox renders them. From[ MapBox doc](https://www.mapbox.com/android-docs/map-sdk/overview/runtime-styling/#sources):

> A benefit of having your data inside a GeoJSON source is that you can update, remove, or add additional features inside the source at any time, providing a solution to animating data in your map through the Runtime Styling API. For example, using an Android ValueAnimator, you can move a feature by updating its coordinates within the GeoJSON data.

But I don't know how to do it, tried to search on internet and SO but got nothing, does anyone know how to do it? Thanks.

(Sorry if this is not the right place to post my issue)

**Comment by langsmith** [comment]
Hey @viettanbkdn , thanks for using Mapbox. Did you manage to figure this out or not yet?

**Comment by langsmith** [comment]
Closing for now because of no response. Will re-open if conversation picks back up.

**Comment by zongyunfeng** [comment]
I find that ios and js both have an example shows how to animate a line from start point to end point, but android demo didn't have one, can android sdk do the same thing?

**Comment by langsmith** [comment]
Hey @zongyunfeng , thanks for looking into Mapbox.

See https://github.com/mapbox/mapbox-android-demo/pull/998 and https://github.com/mapbox/mapbox-android-demo/pull/973.
