### ISSUE TITLE
Separate strings.xml into multiple resources for Transifex

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-android-demo#458]
The Transifex project currently contains a single resource, strings.xml, with a whopping 1,550 words in 274 strings. Many of these strings are obscure or less important to translate, and the demo descriptions in particular require much more concentration to translate than other UI strings. Translators have little guidance as to the most important strings to translate, contributing to translator fatigue.

Does the Android localization system make it possible to split strings.xml into multiple resources? We could then mark certain resources as more or less important in Transifex. That would give translators natural, intermediate goals to work towards.

/cc @langsmith @cammace

**Comment by cammace** [comment]
We can create as many `foobar_string.xml` files as we want (as long as they are in the values folder) and reference the string exactly the same in code using `R.string.xyz`.
