### ISSUE TITLE
please delete the LocationLayerPlugin example

### ISSUE THREAD

**Issue by nielsfalk** [mapbox/mapbox-android-demo#465]
So my location is not moving at all. It cost me almost a day to find out that all obsolete code can be replace with this line
`mapView.getMapAsync { map -> map.myLocationViewSettings.isEnabled = true}`

**Comment by langsmith** [comment]
Thank you for the suggestion @nielsfalk . I will look into improving the app with your thought. Closing as this issue isn't causing the app to crash or anything
