### ISSUE TITLE
How to get User location LatLng!

### ISSUE THREAD

**Issue by houcinenouri06** [mapbox/mapbox-android-demo#47]
mapView.setMyLocationEnabled(true); Is done.

but mapView.getMyLocation() returns always null.

all i want is that mapView.getMyLocation() returns a real location so i can getLatitude() and getLongitude() from the returned location.

Thank you !!

**Comment by tobrun** [comment]
Could test with adding a location listener and see if you are receiving any updates there?
Could be related to not having the correct permissions in your `AndroidManifest`

```java
    mMapView.setOnMyLocationChangeListener(new MapView.OnMyLocationChangeListener() {
            @Override
            public void onMyLocationChange(@Nullable Location location) {
                if(location!=null){
                    // do something with location
                }
            }
        });
```

**Comment by bleege** [comment]
@houcinenouri06 We'll need to know a bit more about your app's setup (is it requesting location permissions?, which version of the SDK is it using?, what android device is it being tested on?, etc) before we can offer much assistance.

Also, for Mapbox Android SDK questions your best bet is to ask them [on that project's repository](https://github.com/mapbox/mapbox-gl-native/).

**Comment by cammace** [comment]
@houcinenouri06 assuming the issue has been resolved, the SDK has changed a bunch since this ticket was opened, closing for now!

**Comment by HridaySarma** [comment]
Wow ! This was really helpful
