### ISSUE TITLE
Picture in picture example crashes when using it in API 24-

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-android-demo#472]
- When launching `PictureInPictureActivity` in a device with API level under 24 the app crashes.

[`enterPictureInPictureMode`](https://developer.android.com/reference/android/app/Activity.html#enterPictureInPictureMode()) was added in API level 24 so adding `@TargetApi(Build.VERSION_CODES.N)` in the method which calls `enterPictureInPictureMode` should fix the crash.

**Comment by tobrun** [comment]
since the `PictureInPictureActivity` isn't usefull for pre API level 24, I'm suggesting to hide it in the overview of examples.

**Comment by langsmith** [comment]
Great, thanks

**Comment by langsmith** [comment]
@tobrun, how do you feel about hiding it if the device is pre level 24?

**Comment by langsmith** [comment]
ok, @tobrun has confirmed that he and I are thinking the same thing by our comments above. I will do a check for the device's version and show the example accordingly.

**Comment by langsmith** [comment]
The example currently has 

```java
addPictureFab.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View view) {
        try {
          enterPictureInPictureMode();
        } catch (Exception exception) {
          Toast.makeText(PictureInPictureActivity.this, R.string.no_picture_in_picture_support,
            Toast.LENGTH_SHORT).show();
        }
      }
    });
```

The problem is that `enterPictureInPictureMode` doesn’t throw any exception, so the `try/catch` is useless.
