### ISSUE TITLE
Acer Chromebook R13 not able to install through Google Play

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#473]
When trying to install the demo app through Google Play on a Acer Chromebook R13.

I'm seeing:

 - `Your device isn't compatible with this version`

**Comment by langsmith** [comment]
@tobrun , you're seeing this in the Play Store like 👇 , correct ?

![screen shot 2017-09-21 at 5 14 08 pm](https://user-images.githubusercontent.com/4394910/30724079-52b0f08e-9ef0-11e7-9f82-df5a18fa392f.png)

**Comment by langsmith** [comment]
For self reference

[https://developer.android.com/topic/arc/index.html](https://developer.android.com/topic/arc/index.html)

[https://android-developers.googleblog.com/2017/09/optimize-your-android-apps-for.html](https://android-developers.googleblog.com/2017/09/optimize-your-android-apps-for.html)

**Comment by langsmith** [comment]
Also @tobrun , do you own this Chromebook? Asking so that I know whether you'd be able to help easily test whether the app can be downloaded or not after I make changes.

**Comment by langsmith** [comment]
[Probably doesn't mean much, but it looks like the R13 was still in Beta as of last June](https://productforums.google.com/forum/#!topic/chromebook-central/HsUcugEyHMw)

**Comment by langsmith** [comment]
From link ☝️ 

> I’m trying to download an app on the Google Play store and getting an error: “Your device isn’t compatible with this version”.

> The app you’re looking at might rely on some hardware or feature that isn’t available in your Chromebook, like cellular connectivity or GPS, or apps (like launchers) that aren’t designed for this kind of interface. This means that you may not see apps like Whatsapp (which needs cellular) or Pokemon Go (which needs GPS).
