### ISSUE TITLE
Add exponential backoff

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#494]
When the app is started up, the user is triggered to create or sign into their mapbox account. While it's a great feature to attract new mapbox users. It's also annoying when you don't want to use this. The dialog is shown for every app launch. To improve UX arround this, I'm suggesting adding exponential backoff to this flow so that I'm not triggered constantly (but only once in a while).

cc @zugaldia

**Comment by tobrun** [comment]
More information about exponential backoff [here](https://en.wikipedia.org/wiki/Exponential_backoff).

**Comment by zugaldia** [comment]
Alternatively, we could add a checkbox with a "don't show this screen again" while keeping the possibility to log in open through the side menu or the settings page.

**Comment by langsmith** [comment]
>Alternatively, we could add a checkbox with a "don't show this screen again" while keeping the possibility to log in open through the side menu or the settings page.

Both added in #1033
