### ISSUE TITLE
Add OnClickListener on Layer

### ISSUE THREAD

**Issue by ac-opensource** [mapbox/mapbox-android-demo#501]
Similar to how Google Maps handle clicking on layer

https://developers.google.com/maps/documentation/android-api/utility/geojson#click

**Comment by langsmith** [comment]
Hi @ac-opensource , thanks for using Mapbox.

Check out [this demo app example](https://github.com/mapbox/mapbox-android-demo/blob/112c80a2816c512e5ea7c0459fcf28f96e4fc811/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/ClickOnLayerActivity.java). It draws a GeoJSON polygon and then delivers a toast when the polygon is tapped. Sounds like what you're looking for. Please re-open this ticket if not!

**Comment by caopeng000** [comment]
How to judge whether a latitude and longitude is in a geographical fence

**Comment by amir169** [comment]
What about vector tiles (*.pbf)?
Can I query on features inside a vector tile?
