### ISSUE TITLE
Changing marker clickable area

### ISSUE THREAD

**Issue by mecoFarid** [mapbox/mapbox-android-demo#502]
Hi. I'm trying to reduce a clickable area of a marker to its very bounding-box. What I'm trying to achieve is to cut out any clickable offset from a marker, so that only direct clicks on bounding-box of a marker will trigger `onMarkerClicked()`. Please refer to the .gif file provided below. As you can see, marker offset occupies very rich area indeed, where well far-away clicks from marker trigger `onMarkerClicked()`. Please note that I have placed my marker files directly into drawable (not one of those screen-resolution-dependent folders) to make a marker appear bigger in size as there's no programmable solution **to scale a marker dimensions up**.
P.S. I've used one of the markers from Mapbox demo app, where there's transparent area under marker icon. Firstly, I suspected that causes issue and cut the transparent area from a marker. However, that didn't solve the issue, instead caused a new problem, dispositioning marker from an actual location by about 10-20 meters (in map-scale) on a map. 
Marker used: https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/res/drawable-xxhdpi/yellow_marker.png

![mapbox_marker](https://user-images.githubusercontent.com/17815721/31311882-d603c1c2-abc6-11e7-83da-f0e4d3550140.gif)

**Comment by langsmith** [comment]
hey @mecoFarid , what version of the Mapbox Maps SDK are you using?

**Comment by langsmith** [comment]
cc @tobrun

**Comment by tobrun** [comment]
With latest releases of the Mapbox Android SDK we have support for hit testing the bounds of the marker so this issue should happen anymore. More details in this PR: https://github.com/mapbox/mapbox-gl-native/pull/9424.
