### ISSUE TITLE
geo refencing

### ISSUE THREAD

**Issue by caopeng000** [mapbox/mapbox-android-demo#514]
How to judge whether a latitude and longitude is in a geographical fence

**Comment by langsmith** [comment]
Hi @caopeng000 ,

Besides @tobrun 's [response to this question in gl-native](https://github.com/mapbox/mapbox-gl-native/issues/10311#issuecomment-340204292), you should also check out [this current example in the demo app](https://github.com/mapbox/mapbox-android-demo/pull/402)
