### ISSUE TITLE
Add turf.buffer example

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#515]
_Originally suggested to be added in the Mapbox Java test app but this app will no longer exist in 3.0._ Read https://github.com/mapbox/mapbox-java/issues/146 for more on the background.

---

We hear from @morganherlocker that `turf.buffer` uses `jsts` under the hood which is in turn a port of the [JTS](http://www.vividsolutions.com/jts/JTSHome.htm) Java library:

> Re: buffers. GEOS' buffer is functionally equivalent to turf's (really JSTS') implementation. They are both ports of JTS (Java); JSTS being JavaScript and GEOS being C++. These might be easier to work with on Android and iOS.

We don't want to add JTS as a dependency of MAS (at least not yet) because it'll likely bring a large number of methods with it, which is something we want to avoid on Android because of the 64K methods limit.

However, we could bring JTS to the Test App and show how to use its buffer functionality to developers. We'd want to mimic the `turf.buffer` API when building the example, i.e.: `TurfTransformation.buffer(Feature feature, double radius, String units)`.

/cc: @cammace

**Comment by langsmith** [comment]
Closing because there are no plans to bring port turf buffer to Java. https://github.com/mapbox/mapbox-java/blob/master/docs/turf-port.md

 Can re-open when that has happened.
