### ISSUE TITLE
Snapshotter example

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-android-demo#523]
Add an example of Snapshotter to android demo.
@ivovandongen  already got [a working example in the Maps SDK test app](https://github.com/mapbox/mapbox-gl-native/blob/e0a305247abcf58c4d1d0ef234d7a9b1ba768554/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java)

**Comment by zugaldia** [comment]
Another good way to showcase the snapshotter in the demo app is using other Android components that naturally take an image, like notifications.

**Comment by osana** [comment]
Did a first cut at a snapshotter example in branch osana-523
At there is just one snapshot that is displayed in top half of a page.

It would be great to have multiple snapshots done which are put in a List. 
Pressing on each item in the list could bring to a page with an interactive map loaded at the same location as the snapshot and with the same style.

For example, List of National Parks.

cc @zugaldia @langsmith

**Comment by langsmith** [comment]
👍 I'm fine with whatever you wanna' go with @osana . One thing to consider is that your described example would be the first example where we go an extra activity deep. I'm not sure if our current set up easily supports this, so we'll have to 🔎 this a little bit to make sure there are no problems with activity navigation and all. Shouldn't be hard though.

Right now, it's: list of examples in a section –– tap –> specific example 

Suggested snapshotter flow: list of examples in a section –– tap –> specific snapshotter example –– click–> interactive map

**Comment by zugaldia** [comment]
Thank you @osana for kickstarting this effort! We're now continuing this work on https://github.com/mapbox/mapbox-android-demo/pull/548, which adds a new section to the demo app dedicated to static image generation using the Snapshotter API.
