### ISSUE TITLE
In RTL mode the info button stays at the left side

### ISSUE THREAD

**Issue by csipetcsabi** [mapbox/mapbox-android-demo#529]
In RTL mode  (arabic pos) the mapbox icon appears on the right side properly, but the info button stays at the left side.

![mapbox_bug](https://user-images.githubusercontent.com/591222/32546643-158db416-c480-11e7-872c-f5a4aa8a7d78.png)

**Comment by langsmith** [comment]
Closing this ticket because this is an issue with the Mapbox Maps SDK for Android, rather than the demo app specifically

Equivalent ticket made in `gl-native` repo: [https://github.com/mapbox/mapbox-gl-native/issues/10431](https://github.com/mapbox/mapbox-gl-native/issues/10431)
