### ISSUE TITLE
Update SymbolLayer example

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-android-demo#530]
Currently, the [`SymbolLayer` example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/RecyclerViewSymbolLayerActivity.java) within the Labs section looks like this:

![screenshot_20171108-091444](https://user-images.githubusercontent.com/6964/32553972-53cdf566-c466-11e7-93b6-c87a05e53f64.png)

While it's a great first iteration, it doesn't take full advantage of the existing API. In particular, we'd like to update this sample to:

1. Show text labels alongside the icons, which respond to click events.
1. Change the icon size on tap to highlight selected state.
1. Use different icons for different markers.

cc: @tobrun @langsmith

**Comment by zugaldia** [comment]
Note that there currently is a PR open for this example: https://github.com/mapbox/mapbox-android-demo/pull/509.

**Comment by langsmith** [comment]
_Note:_ The screenshot in OP is of the [RecyclerViewOnMapActivity](https://github.com/mapbox/mapbox-android-demo/blob/f564efb2afdf644104f8a01b32dc73b87e59d658/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/RecyclerViewOnMapActivity.java), however the example that OP actually wants adjusted is [**RecyclerViewSymbolLayerActivity**](https://github.com/mapbox/mapbox-android-demo/blob/93f8c37b6b07955fe6c574f82090dcc197b6f49c/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/RecyclerViewSymbolLayerActivity.java)

In `RecyclerViewSymbolLayerActivity`, the selected marker does increase in size and change colors. The changes could probably be improved/refactored though, to go along with the new text label addition.


<img width="356" alt="screen shot 2017-11-08 at 6 32 02 am" src="https://user-images.githubusercontent.com/4394910/32554460-b51ebf0c-c44e-11e7-8032-396c04f3369d.png">

**Comment by langsmith** [comment]
#538 fixed this
