### ISSUE TITLE
Cirlce Layer

### ISSUE THREAD

**Issue by dino9** [mapbox/mapbox-android-demo#535]
how to create a Circle for some radius in meters. Couldn't find a single source in sample app/online. Please help me in this.

**Comment by langsmith** [comment]
Hi @dino9 , thanks for using Mapbox. These examples in the demo app use a circle layer: [https://github.com/mapbox/mapbox-android-demo/search?utf8=%E2%9C%93&q=CircleLayer&type=](https://github.com/mapbox/mapbox-android-demo/search?utf8=%E2%9C%93&q=CircleLayer&type=)

You'll want to use a `circleRadius` property. An example of its use can be found here: [https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/StyleCirclesCategoricallyActivity.java#L55-L63](https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/StyleCirclesCategoricallyActivity.java#L55-L63)
⬆️ is an example of run-time styling. Data-driven styling is also another option if you want the size of the circles to be based on a data set


[You can just pass in a float](https://www.mapbox.com/android-docs/api/map-sdk/5.2.0/com/mapbox/mapboxsdk/style/layers/PropertyFactory.html#circleRadius-java.lang.Float-) if you want to hardcode a size for the circles.
