### ISSUE TITLE
Traffic plugin crash

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#536]
cc @tobrun 

[Traffic plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-traffic) example crashes when I try to open it. Crashing on `master`

Seeing this in the log when it crashes

```java
11-12 07:49:20.132 25836-25836/com.mapbox.mapboxandroiddemo.debug A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 25836 (droiddemo.debug)
                                                                          
                                                                          [ 11-12 07:49:20.132   626:  626 W/         ]
                                                                          debuggerd: handling request: pid=25836 uid=10751 gid=10751 tid=25836
```

**Comment by langsmith** [comment]
The plugin's working fine in the plugins test app traffic activity. So strange. I've tried it the demo app way in a separate project, and the separate project gets the same crash.

**Comment by tobrun** [comment]
Apologies for missing this, the traffic plugin will require the same SDK update and release as the LocationLayer (an update above 5.2.0-beta.4?).

**Comment by langsmith** [comment]
Ok, thanks for letting me know.

**Comment by Guardiola31337** [comment]
I think https://github.com/mapbox/mapbox-android-demo/pull/588 solved OP.
Could you retest?

If it's not an issue anymore, we're good to close here.

cc/ @langsmith @tobrun

**Comment by langsmith** [comment]
Plugin's working great 🍾
