### ISSUE TITLE
When activity is recreated, adding layer has no effect. 

### ISSUE THREAD

**Issue by uburoiubu** [mapbox/mapbox-android-demo#537]
I have this issue: after screen orientation I try to  (re)add layers, and that has no effect. If I look for a layer in `mapBoxMap.getLayer(String id)`, I get `null`, even if just before that I added this layer to the map.

**Comment by langsmith** [comment]
Hi @uburoiubu . Thanks for using Mapbox 

This is default behaviour as each layer/source is linked to one style. There are techniques to solve this as we already do for a couple of our plugins.

First you need to listen to map change events https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java#L78, in particular you are interested in the DID_FINISH_LOADING_STYLE event as show in https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java#L116. Once that happens you need to call your method again to recreate and re-add those layers/sources.
