### ISSUE TITLE
Question: ClickListener for all Layer Types

### ISSUE THREAD

**Issue by bradmartin** [mapbox/mapbox-android-demo#540]
Thanks for the awesome open source project mapbox is :) I know there is a huge API surface with Mapbox so I imagine not all use cases could possibly be covered with documentation/examples. I've been working on a project for over a month now and I have been unsuccessful in implementing what I need with the android/ios SDKs.

I have a couple of different issues I'm working through. The current one is related to adding click listeners for multiple types of layers. I've successfully implemented the code from [this](https://github.com/mapbox/mapbox-android-demo/issues/305#issue-224707108) to add a map click listener and get the featureList and determine the layer clicked. However this does not seem to work with CircleLayers or FillLayers. 

What is the optimal way to set a click listener for all layer types to return the layer data? Is there anything planned to add a click listener on the layer themselves and not have to handle this on the mapClickListener event? 

Below is my current implementation which will return the featureList populated with data if it's a `LineLayer`. One other thing, not an issue, but obviously you might question the code. This app is a NativeScript app so I'm using TypeScript and consuming the native SDKs. That is not an issue itself, the issue is understanding and figuring out the optimal way to consume the android SDK itself in the scenario below. Thanks for your time.

``` typescript
this._mapboxMap.setOnMapClickListener(
        new com.mapbox.mapboxsdk.maps.MapboxMap.OnMapClickListener({
          onMapClick: latLng => {
            try {
              const pointf = this._mapboxMap
                .getProjection()
                .toScreenLocation(latLng);
              const rectF = new android.graphics.RectF(
                pointf.x - 10,
                pointf.y - 10,
                pointf.x + 10,
                pointf.y + 10
              );
              const featureList = this._mapboxMap.queryRenderedFeatures(
                rectF,
                null,
                [layer.GLSource]
              ) as java.util.List<any>;
              console.log(`featureList`, featureList);
              if (featureList.isEmpty()) {
                console.log("*** featureList is empty ***");
                return;
              }
              for (let iter = featureList.iterator(); iter.hasNext(); ) {
                const x = iter.next();
                const data = JSON.parse(x.toJson());
                console.log(`feature data = ${data}`);
                debugger;
                if (data.properties && data.properties.dynaID) {
                  console.log(`dynaID = ${data.properties.dynaID}`);
                  this._showMapDetailLayout(data.properties.dynaID);
                }
                // get the detail and open the hidden layout
              }
            } catch (err) {
              this._log.logSentry(err);
            }
          }
        })
      );
```

**Comment by langsmith** [comment]
Hey @bradmartin  thanks for your patience on this

> However this does not seem to work with CircleLayers or FillLayers.

`queryRenderedFeatures` can work on those layers in certain implementations, but it doesn't always work. See https://github.com/mapbox/mapbox-gl-native/issues/9686

>  Is there anything planned to add a click listener on the layer themselves and not have to handle this on the mapClickListener event?

There are no plans for this at this moment. You could always [create a ticket in gl-native](https://github.com/mapbox/mapbox-gl-native/issues) so that it's officially in the issue queue and bit more on our radar. This functionality could also be a nice [plugin](https://github.com/mapbox/mapbox-plugins-android) too.
