### ISSUE TITLE
The snapshotter demos in the Test App and in the Demo App both intermittently fail without errors

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-android-demo#550]
If you take a look at "Snapshot Grid" under "Image Generator" in the demo app, sometimes when you open it, the map images never render, and no errors are logged. When you kill the app and restart it, the demo works again.

cc: @tobrun @zugaldia

**Comment by tobrun** [comment]
Fix in https://github.com/mapbox/mapbox-gl-native/pull/10556 and will be released with v5.2.1
