### ISSUE TITLE
Deprecated :: mMapboxMap.setMyLocationEnabled(true); 

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-android-demo#551]
mMapboxMap.setMyLocationEnabled(true); is deprecated.

What is the replacement??

**Comment by mf-mindcrewtech** [comment]
Anyone??

**Comment by langsmith** [comment]
Hi @mf-mindcrewtech , the replacement for this is to use the location layer plugin: https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer

Here's its example activity in our Android demo app: https://github.com/mapbox/mapbox-android-demo/blob/a411fa95cd71c1b90a30895060b319310444aebb/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java


cc @lilykaiser
