### ISSUE TITLE
ISSUE :: Mapbox mapview showing the same view in multiple fragments

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-android-demo#552]
Hi all,

I am using mapbox mapview in my fragment classes. So the scenario is as follows,

Fragment A having mapview and Fragment B having mapview.

When I add fragment B on Fragment A, so fragment A map are showing/overlapping on fragment B mapview.
What is the issue????

I dont know, how to clear previous map. Any help really appreciate.

**Comment by langsmith** [comment]
@mf-mindcrewtech , I'm not sure exactly what you're trying to achieve. This isn't an issue with the actual android demo app.


`mapboxMap.clear();` will clear a Mapbox map


In case you haven't seen it, [our Android demo app has an example of setting up a support map fragment](https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/basics/SupportMapFragmentActivity.java)



Maybe I can provide more help if you can give me a better sense of what you want the UI to look like and/or how you want it to behave.
