### ISSUE TITLE
Question :: Change mapbox building color

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-android-demo#561]
I tried this code from ref doc [ https://www.mapbox.com/help/android-runtime-styling-intro/ ]

final Layer building = mapboxMap.getLayer("building");
if (background != null) {
background.setProperties(PropertyFactory.fillColor(Color.parseColor("#FF4081"))
);
}

But this is not working, can anyone please tell me how to achieve with android sdk.

![screen shot 2017-11-30 at 10 49 09 am](https://user-images.githubusercontent.com/25820087/33415402-52052f9e-d5bc-11e7-8e0c-34d82fdd0654.png)

**Comment by langsmith** [comment]
@mf-mindcrewtech , this has nothing to do with the demo app. We've got solid documentation and deep help section at [https://www.mapbox.com/help/](https://www.mapbox.com/help/). See [https://www.mapbox.com/help/android-runtime-styling-intro/#change-the-water-color](https://www.mapbox.com/help/android-runtime-styling-intro/#change-the-water-color) for a similar example of what you're trying to do.

You're close, but you seem to have made a simple mistake in your code. You want to color the buildings to the dark grey color? In the code that's in your ticket above, you're trying to change the fill color on some sort of object that you call `background`. You should be calling `setProperties()` on the `building` Layer object. Try `building.setProperties(PropertyFactory.fillColor(Color.parseColor("#FF4081"))`

So it'd be:
 
```java
final Layer building = mapboxMap.getLayer("building");
if (background != null) {
building.setProperties(PropertyFactory.fillColor(Color.parseColor("#FF4081"))
);
}
```

By the way, #FF4081 [is a bright pink color](http://www.color-hex.com/color/ff4081) and not the dark grey that the buildings are colored in the screenshot above.

**Comment by mf-mindcrewtech** [comment]
Yes, this is just demo pink color and sadly this was still not working :(

**Comment by langsmith** [comment]
Maybe you don't have a `building` layer in your particular map style? Are you using a custom map style? 

Run the code below in `onMapReady()` to print out a list of the map's layers and then post the logcat list that is printed out:

```java
for (Layer singleMapLayer : mapboxMap.getLayers()) {
          Log.d("ACTIVITY-NAME", "onMapReady: layer name = "+ singleMapLayer.getId());
        }
```
Can you share more code for me to maybe see why it's not working?

**Comment by mf-mindcrewtech** [comment]
Hi LangSmith, Don't know but this was working now.

I just re-install the app and its showing black color on buildings.

Thanks for your kind help 👍

**Comment by langsmith** [comment]
👍 🍾  glad to hear it @mf-mindcrewtech
