### ISSUE TITLE
Add downloadable font example

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#562]
With https://github.com/mapbox/mapbox-gl-native/pull/10522, we are adding support for local fonts so they don't need to be downloaded as part of the style. A nice example for this feature would be to combine this with the [Downloadable Fonts](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts.html) feature that was announced at Google I/O this year. For gl-native testing will probably just package the font in the assets folder.

**Comment by langsmith** [comment]
CLosing because I don't think this warrants a demo app example
