### ISSUE TITLE
Error:(13, 39) error: package com.mapbox.directions.v5.models does not exist

### ISSUE THREAD

**Issue by trinhvanminh2009** [mapbox/mapbox-android-demo#564]
Cannot resolve symbol 'directions'
`import com.mapbox.directions.v5.models.DirectionsResponse;
import com.mapbox.directions.v5.models.DirectionsRoute;`
My compile 
` compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0'
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'`
Any way to solve this problem. My project working perfectly a few hours ago.

**Comment by langsmith** [comment]
Hi @trinhvanminh2009 , thanks for reaching out and for using Mapbox! Please just use one compile line for the navigation SDK 

EITHER the stable or the SNAPSHOT version. Not both in your gradle file.

**Stable:** `0.7.1`** is the latest stable version: https://github.com/mapbox/mapbox-navigation-android#getting-started

**Snapshot**: https://github.com/mapbox/mapbox-navigation-android#using-snapshots if you'd like to you the snapshot.
