### ISSUE TITLE
Fix black screen when scrolling wearable map in one direction

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#565]
Weird black screen when trying to scroll the map in one direction:
![ezgif com-resize](https://user-images.githubusercontent.com/4394910/33495129-0c113712-d67a-11e7-8079-6902af041118.gif)

_**Wear dependencies**_

![screen shot 2017-12-01 at 9 30 44 am](https://user-images.githubusercontent.com/4394910/33495225-67522d3e-d67a-11e7-949a-5fd49368d2d9.png)
![screen shot 2017-12-01 at 9 30 39 am](https://user-images.githubusercontent.com/4394910/33495226-676ed09c-d67a-11e7-8d6f-6dcee5316e52.png)

**Comment by cammace** [comment]
The activity needs to go into a `<android.support.wear.widget.SwipeDismissFrameLayout/>` container instead of a frameLayout.

**Comment by langsmith** [comment]
Thanks @cammace
