### ISSUE TITLE
remove base map

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-android-demo#587]
Hi
I'm working on mapbox android sdk. I can show our map tiles ( png raster tiles ), but some districts are transparent and in that places mapbox map appears. In another same project with google map i have done this and google has an option that name is :

`googleMap.setMapType(GoogleMap.MAP_TYPE_NONE);`

that remove the default google map and only show my tiles but there is no option like this in mapbox android and i'm getting surprised that this huge sdk doesn't have this basic option or i couldn't find easily. Is there anyone that can help me to solve this ?

It's good to say that i have removed all of layers and sources and annotations from mapbox then add our own raster tileset :

```
 for (int i = 0; i < mapboxMap.getLayers().size(); i++) {
        mapboxMap.removeLayer(mapboxMap.getLayers().get(i));
    }

    for (int i = 0; i < mapboxMap.getSources().size(); i++) {
        mapboxMap.removeSource(mapboxMap.getSources().get(i));
    }

    for (int i = 0; i < mapboxMap.getAnnotations().size(); i++) {
        mapboxMap.removeAnnotation(mapboxMap.getAnnotations().get(i));
    }



webMapSource = new RasterSource(
            "web-map-source",
            new TileSet("tileset", "ourownwebsite.com?" +
                    "bbox={bbox-epsg-3857}" +
                    "&service=WMS" +
                    "&version=1.1.0" +
                    "&EXCEPTIONS=application/vnd.ogc.se_inimage" +
                    "&request=GetMap" +
                    "&layers=test:GSLD256" +
                    "&width=256" +
                    "&height=256" +
                    "&srs=EPSG:3857" +
                    "&format=image/png"), 256);

    mapboxMap.addSource(webMapSource);         
    // Add the web map source to the map.
    RasterLayer webMapLayer = new RasterLayer("web-map-layer", "web-map-source");
    mapboxMap.addLayer(webMapLayer);
```

**Comment by tobrun** [comment]
@AliKhoshraftar mapbox-streets is automatically loaded if you do not provide a style-url. You are able to create an "empty" style in Mapbox Studio and use that style instead (note that you can also configure your raster source there as well, no need to do it programmatically). 

Let us know if you have more questions, closing as answered.
