### ISSUE TITLE
Update the traffic plugin dependency when a new version is available

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-android-demo#589]
Per #588 the traffic plugin version was bumped to use `0.4.0-SNAPSHOT`.

- We should update the [traffic demo app dependency](https://github.com/mapbox/mapbox-android-demo/blob/master/gradle/dependencies.gradle#L21) and publish a new version of the demo app when a new version of the traffic plugin is available.

cc/ @langsmith @LukasPaczos

**Comment by langsmith** [comment]
Yes, several projects are waiting for an improved and working version of the traffic plugin 👍

**Comment by langsmith** [comment]
_Note:_ `0.4.0-SNAPSHOT` of the plugin is working fine for now. We can do new release when a stable `0.4.0` is ready

**Comment by Guardiola31337** [comment]
> _Note:_ `0.4.0-SNAPSHOT` of the plugin is working fine for now. We can do new release when a stable `0.4.0` is ready

Yeah, because of that I opened the ticket. This way we don't forget 😅

**Comment by langsmith** [comment]
Traffic plugin is up-to-date and working fine in the demo app
