### ISSUE TITLE
onInfoWindowClick not firing up

### ISSUE THREAD

**Issue by pepOSgh** [mapbox/mapbox-android-demo#598]
Hi,
 I'm using **mapbox-android-sdk 5.1.4** and I'm trying to customize the Info Window. 

I'm using the following:
` mapboxMap.setOnInfoWindowClickListener(new MapboxMap.OnInfoWindowClickListener() {`
            `@Override`
            `public boolean onInfoWindowClick(@NonNull Marker marker) { `              
                `Toast.makeText(getContext(), "Clicked a windowInfo", Toast.LENGTH_SHORT).show();`
                 `return true;`
          ` }`
       ` });`

The map sets the listener but when an Info window is clicked nothing happens.

I'm also having the same issue with the **InfoWindowLongClickListener**.

Curious thing though, the **InfoWindowCloseListener** does works.

thanks

**Comment by tobrun** [comment]
@pepOSgh thank you for reporting your issue, could you check the code [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowActivity.java#L96) and look into how this is different as your setup? I validated with 5.3.2 codebase and the InfoWindow click is correctly executed.

**Comment by tobrun** [comment]
I'm going ahead and close this as this is not the right repository to report bugs. Feel free to create a new ticket in https://github.com/mapbox/mapbox-gl-native/ if your issue is still reproducible with 5.3.2 and your code matches the example provided above.

**Comment by pepOSgh** [comment]
@tobrun thanks.
