### ISSUE TITLE
error com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by vlong5461** [mapbox/mapbox-android-demo#604]
use implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.1'

error com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

Project used v4, v7, design package, is not a conflict with the mapbox? mapbox how to remove these packages?
How to solve the problem?
Thank you!

**Comment by tobrun** [comment]
@vlong5461 thank you for reaching out, if you want to analyse gradle dependencies and which versions are used by which dependency. You can use the `./gradlew :module_name:dependencies` to list and see which gradle selects. Closing as this is not an SDK issue.
