### ISSUE TITLE
Add temperature conversion example

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#616]
A useful example to test the expression code integration would be take a dataset that expresses temperature in kelvin or celsius and converting that to it's counterpart.

Formula for this conversion is:

```
T(K) = T(°C) + 273.15
```

**Comment by langsmith** [comment]
Resolved by @osana 's #818    (https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ExpressionIntegrationActivity.java#L310-L314) !
