### ISSUE TITLE
Mapview in a recyclerview item

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#624]
An example with a RecyclerView that contains maps and other items, to show how to handle the Map lifecycle events when the Map is in a RecyclerView. Would be good to show a proper way to handle it.

**Comment by tkrami** [comment]
@langsmith is there still a solution for this issue?

**Comment by langsmith** [comment]
Hey @tkrami , thanks for looking into Mapbox. This isn't in the demo app (yet), but there's an example in the Maps SDK test app: https://github.com/mapbox/mapbox-gl-native/pull/13132

**Comment by tkrami** [comment]
Hey @langsmith I still managed to show the map in a RecyclerView item. But now I have another weird issue. When I am using the RecyclerView in a ChildFragment and the mapViews option "        app:mapbox_renderTextureMode="true"" is set, the map is blank.

By setting this flag to false the mapView will be created as accepted, but the app crashes when scrolling the recyclerView.

After debugging I find out that the "onSurfaceCreated" function of the MapView class (https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L284) was never called and so "onMapReady" in my ViewHolderItem never get fired.
