### ISSUE TITLE
How Can i set Pulsing (" marker.setAnchor(0.5f, 1.0f + 2 * t);") not working. in mapbox is there any solution ? or else any other type of animation which can we set on marker with the help of marker marker will bounce on map automatically 

### ISSUE THREAD

**Issue by lovekothari123** [mapbox/mapbox-android-demo#630]
I want to set pulsing on a map means -- when my map will open marker will bounce on map automatically is there any solution for that when we using GOOGLE MAP and we set on " marker.setAnchor(0.5f, 1.0f + 2 * t);"
it will start bounce but this method not supported in map box. if anyone knows this so plz help me thank~you.

**Comment by langsmith** [comment]
Hi @lovekothari123 , thanks for using Mapbox! 

I recommend that you use a `SymbolLayer` and `SymbolLayer` icons. Using runtime styling and the `PropertyFactory` `iconTranslate` method (https://www.mapbox.com/android-docs/api/map-sdk/6.2.0/com/mapbox/mapboxsdk/style/layers/PropertyFactory.html#iconTranslate-com.mapbox.mapboxsdk.style.expressions.Expression-), you can dynamically change its location/"height" above a specific location on the map. The location will be a `Feature` object's coordinates. 

This ticket isn't an actual issue with this demo app, so I'm going to close this ticket. If you'd like to continue a conversation about your specific question, please use the form at https://www.mapbox.com/contact/support/#products/android
