### ISSUE TITLE
Update plugin dependencies

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#634]
The plugins have received some updates in the past week, this tickets to track updating this app with those dependency versions:

- Location Layer 0.4.0
- Places Plugin 0.2.1

**Comment by langsmith** [comment]
Places has been bumped to 0.2.1: https://github.com/mapbox/mapbox-android-demo/pull/633

Location layer bump: https://github.com/mapbox/mapbox-android-demo/pull/642
