### ISSUE TITLE
Example Crashing

### ISSUE THREAD

**Issue by Jayce2177** [mapbox/mapbox-android-demo#641]
I have followed the example for location by just copying and pasting it into my test app, but this line seems to crash it every time :  locationEngine = new LostLocationEngine(LocationPluginActivity.this); with the only error message as : 

03-04 22:09:01.962 11249-11249/? E/Zygote: v2
03-04 22:09:01.963 11249-11249/? E/Zygote: accessInfo : 0
03-04 22:09:02.017 11249-11263/? E/art: Failed sending reply to debugger: Broken pipe
03-04 22:09:07.312 11249-11249/com.tech.gm.testapp E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
03-04 22:09:07.312 11249-11249/com.tech.gm.testapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11249 (m.testapp)

                                                             [ 03-04 
22:09:07.313   527:  527 W/         ]
                                                             debuggerd: handling request: pid=11249 uid=10497 gid=10497 tid=11249

**Comment by langsmith** [comment]
@Jayce2177 , 

Try this new and improved way to get a `locationEngine` object 👇 

`locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();`

Do you still get the same errors/crashing?

**Comment by Jayce2177** [comment]
I had to add these two lines to my build.gradle to make it work. Not sure why this isn't put into the documentation.

compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9'
compile 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.9@aar'

**Comment by Jayce2177** [comment]
@langsmith So I had to try a different way cause my app wouldn't build final apk with those two lines, so I tried your way and now when I go to build my app I get the following errors:

Warning:com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerOptions: can't find referenced class com.google.auto.value.AutoValue
Warning:com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerOptions$Builder: can't find referenced class com.google.auto.value.AutoValue$Builder
Warning:com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerOptions$Builder: can't find referenced class com.google.auto.value.AutoValue
Warning:com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerOptions$Builder: can't find referenced class com.google.auto.value.AutoValue$Builder
Warning:okhttp3.internal.platform.ConscryptPlatform: can't find referenced class org.conscrypt.OpenSSLProvider
Warning:okhttp3.internal.platform.ConscryptPlatform: can't find referenced class org.conscrypt.Conscrypt

This is becoming so frustrating as there is very limited documentation or tutorials and the example apps don't even work without crashing or being able to generate a signed apk.

**Comment by langsmith** [comment]
Ok, thanks for the feedback @Jayce2177 and for your patience. Yes, it can be frustrating at times. Mapbox has a growing number of fine grain Android tools and we're constantly improving our systems to keep things aligned. 

[This pr](https://github.com/mapbox/mapbox-android-demo/pull/643) will be going into `master` soon and it fixes several issues with the app. 

Your original post at the top of this ticket mentions `the example for location`, so my guess is that you're trying to use [the location layer plugin for Android](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer). Is that correct? Are you able to describe what you're trying to ultimately accomplish? 

View the  `LocationPluginActivity` on that pr (branch is `ls-multiple-version-bump-hotfixes`). That has a basic working example of using the location layer plugin for Android. [Here is the `dependencies.gradle` file for that branch/pr](https://github.com/mapbox/mapbox-android-demo/blob/ls-multiple-version-bump-hotfixes/gradle/dependencies.gradle) and [Mapbox dependencies](https://github.com/mapbox/mapbox-android-demo/blob/ls-multiple-version-bump-hotfixes/MapboxAndroidDemo/build.gradle#L89-L100). Like I said, this will all be on `master` very soon.

**Comment by langsmith** [comment]
Also @Jayce2177 , are you experiencing complete app _crashes_ or just the warnings in the log console?

**Comment by Jayce2177** [comment]
@langsmith it won't generate a signed apk file. All I am doing is trying to track the users location, it is so simple with Google maps but I like the way mapbox looks, but I can't seem to get it to generate a signed apk. If I manually install it on my device via run:run app it works, it is when I try to generate the signed apk so I can upload the new file to the playstore that it gets hung up.

**Comment by Jayce2177** [comment]
Well I have to say not pleased, after messing with this for almost a full week with something as simple as showing a map and a users location it doesn't seem to work and I have had to result back to the simple method of Google Maps, maybe in a year when Mapbox is more stable and has updated it's information I will try again. You can go ahead and mark this as closed I guess.

**Comment by langsmith** [comment]
As @LukasPaczos  stated at https://github.com/mapbox/mapbox-gl-native/issues/11400#issuecomment-371075246, this is a proguard issue with the location layer plugin. cc @cammace 

>This is becoming so frustrating as there is very limited documentation or tutorials and the example apps don't even work without crashing or being able to generate a signed apk.

- `master` in this repo should be _much_ more stable now that https://github.com/mapbox/mapbox-android-demo/pull/643 has landed.
- please open a ticket in https://github.com/mapbox/android-docs if you ever think of topics that you think could use more documentation. We are always eager to hear from developers about what subjects could be clarified.
