### ISSUE TITLE
Implement samples into demo app

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#65]
This demo app in its current state only demonstrates a few things that can be done with the SDK. Updating the app to use a listview with separate example activities would both, show off the SDK potential and add another location for sample code. #64 has been opened that will implement these ideas and also prepare for `4.1.0`. What it looks like:

<img src="https://cloud.githubusercontent.com/assets/5652865/15294830/d4de3324-1b5b-11e6-8d48-19c11012a7e6.png" width="300"> <img src="https://cloud.githubusercontent.com/assets/5652865/15295184/5c764ae6-1b5d-11e6-966a-6e444e0dcb7b.png" width="300"> <img src="https://cloud.githubusercontent.com/assets/5652865/15295235/99b132b8-1b5d-11e6-8249-02476e1318e0.png" width="300">

What needs to be done:

- [x] change map styles back to using constant
- [x] static image example not displaying image
- [x] simple offline map example is too simple, not canceling download after leaving activity
- [ ] `readme.md` file needs to be updated
- [ ] prepare screenshots for play store
- [ ] testing!

Examples to be added:
- [x] Bounding box camera (frequently requested)
- [x] MapboxMapOptions example
- [ ] MAS Maki icon
- [ ] View annotation examples
- [ ] User location examples

cc: @bleege @tobrun @danswick @zugaldia

**Comment by bleege** [comment]
Looks like you're making great progress @cammace!  Keep it up!  🚀

**Comment by danswick** [comment]
Been using this as my default reference app for the last week. So far, so good!

**Comment by cammace** [comment]
New demo app been pushed to the play store and tracking of new examples is being done internally, closing ticket!
