### ISSUE TITLE
Add example of minimal InfoWindow with symbol layer 

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#651]
@danswick 's request at https://github.com/mapbox/android-docs/issues/271 was to see 👇 implemented with a symbol layer

![screenshot_20180312-150552](https://user-images.githubusercontent.com/4394910/37312141-20dc18ec-2607-11e8-82ac-3d8110c7517e.jpg)

**Comment by grote** [comment]
There's an example [here](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c#e961), but it seems rather complicated and inflates a custom info window instead of the generic one.

**Comment by langsmith** [comment]
Fyi @danswick and @grote , this moving in #738

**Comment by moorthysubu** [comment]
When tried to show Info window by generating a bitmap from view, Android system throws OutOfMemory when tried to loan 100+ marks in a map, Here view includes textView & Multiple Imageview with SVG source, So how to implement info window in symbol layer without using bitmaps or any other approaches to fix OutOfMemory exceptions,Thanks in advance

**Comment by langsmith** [comment]
Hi @moorthysubu , thanks for using Mapbox! This is an implementation question rather than an issue with the actual demo app.

Please contact the Mapbox Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and they'll get you squared away. Please make sure to include code snippets and/or error messages related to the memory issues.
