### ISSUE TITLE
ISSUE WITH activity_main.xml MAPVIEW STYLING

### ISSUE THREAD

**Issue by jamiewanderi** [mapbox/mapbox-android-demo#652]
![shoot](https://user-images.githubusercontent.com/24609174/37420370-b5b056c4-27c7-11e8-806e-911ae05b342d.JPG)

i followed the official documentation bt am having this issue here.
kindly needs help asap.

**Comment by tobrun** [comment]
replace `mapbox:` xml prefixes with `app:`

**Comment by jamiewanderi** [comment]
Thanks bud @tobrun worked like a charm!
