### ISSUE TITLE
hello,now the demo change the mapstyle with black background. but I want to add the map with white background, How can I do that?

### ISSUE THREAD

**Issue by whyzjl** [mapbox/mapbox-android-demo#665]
hello,now the demo change the mapstyle with black background. but I want to add the map with white background,  How can I do that?

**Comment by langsmith** [comment]
@whyzjl 您好。我不太清楚你的意思，但是，您在XML文件可以改变您的地图模式 https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/res/layout/activity_basic_simple_mapview.xml#L17

您还有问题的话，就问我。谢谢您使用Mapbox!

**Comment by whyzjl** [comment]
你好，我的意思是：地图切换过程中，如果网络慢的情况下，地图背景是黑色的，我觉得体验并不是很好，想改成白色的背景，可以做到吗？

**Comment by langsmith** [comment]
👋 @whyzjl   请读https://github.com/mapbox/mapbox-gl-native/issues/10990

目前，没有办法。对不起。
