### ISSUE TITLE
Add bathymetry example

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#668]
Add an example that uses various FillLayer polygons to show bathymetry data. Similar to something like

![suhodolskoe1-02-00](https://user-images.githubusercontent.com/4394910/38147523-b979712c-3420-11e8-8eed-ee57ac33d8b5.png)

**Comment by langsmith** [comment]
Mapbox blog post about a nautical themed map style which includes bathymetry: https://blog.mapbox.com/designing-north-star-c8574e299c94

**Comment by jorgeale90** [comment]
I would like to know if you have created an example of barimetry with mapbox, I want to do something like a nautical chart for a web page and I would like to do it with this great online map provider. Thank you
