### ISSUE TITLE
how to get  a click event when i touch an exist marker like  building  ico on the map

### ISSUE THREAD

**Issue by hellopyj** [mapbox/mapbox-android-demo#68]

**Comment by 1ec5** [comment]
There’s [`OnMapClickListener`](https://www.mapbox.com/android-sdk/api/4.0.1/com/mapbox/mapboxsdk/maps/MapboxMap.OnMapClickListener.html), but getting information about a building at the point that was clicked isn’t supported at the moment. Once mapbox/mapbox-gl-native#352 is fixed, it’ll be relatively straightforward for you to look up the underlying data within your `OnMapClickListener`.
