### ISSUE TITLE
when I download the offlineMap

### ISSUE THREAD

**Issue by whyzjl** [mapbox/mapbox-android-demo#681]
when I download the offlineMap, if the maptile exceed 6000, log will show: "Mapbox tile count limit exceeded“，How can I modify the limit？

**Comment by langsmith** [comment]
👋 Hi @whyzjl . I'm glad that you're able to get offline mapping working. You will need [a Mapbox enterprise plan](https://www.mapbox.com/pricing/) if you want more than 6,000 map tiles. 

Please read https://www.mapbox.com/help/mobile-offline/#tile-ceiling--limits for more information about offline tile limits and [contact Mapbox sales](https://www.mapbox.com/contact/sales/?page=pricing) to discuss your goals for offline mapping.
