### ISSUE TITLE
User Location not appearing, unless you go out and back to the app

### ISSUE THREAD

**Issue by renatosc** [mapbox/mapbox-android-demo#682]
Just tried MapBox for the first time and I found an issue regarding showing the user's current location. 

That bug happened both on the map-android-demo app (this repo) and also when I manually implemented the SDK following the site instructions.

The LocationLayerPlugin works fine, the location is found and the map position is updated to the current location, only the "dot" icon representing the user's position in the map that does not appear. 

If you exit the app and come back (could be just switching to another app or even leaving the app without closing it and opening it again) the dot appears.

This is happening under a Nexus 5X, I was not able to test on another device to check if it is a device specific issue.

**Comment by langsmith** [comment]
@renatosc , thanks for the heads up and for using Mapbox. This is a plugin issue and we're discussing it at https://github.com/mapbox/mapbox-plugins-android/issues/424 and https://github.com/mapbox/mapbox-plugins-android/pull/428

**Comment by renatosc** [comment]
Ah, they were reported on another repo... that is why I didn't find those issues here before I created this one. Thank you for letting me know.
