### ISSUE TITLE
Add "marching ants" traffic dash array movement

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#688]
Something similar to 👇 
![39113009-1c8e9fb4-468f-11e8-8a85-f6bcd7fa4566](https://user-images.githubusercontent.com/4394910/39140398-4bd20474-46d9-11e8-8e1c-365466e28dfe.gif)

Start with the Navigation Preview Night style, then add a line layer with a simple `lineDashPattern` and a `lineColor` expression that’s a tint of the underlying traffic layers’ colors. Make fast traffic brighter to appear faster as it moves. Using runtime styling, update the `lineDashPattern` on a timer to expand or contract the first gap in the pattern.

With expressions:

```json
[
  'interpolate',
  ['exponential', 1.5],
  ['zoom'],
  6, 1,
  13, 4,
  18, [
    'match',
    ['get', 'class'],
    ['motorway', 'trunk'], 18,
    'primary', 11,
    ['secondary', 'tertiary'], 7,
    0
  ],
  20, [
    'match',
    ['get', 'class'],
    ['motorway', 'trunk'], 33,
    'primary', 18.5,
    ['secondary', 'tertiary'], 14,
    0
  ]
]
```

**Comment by langsmith** [comment]
Swift version

```swift
let stops: [Float: Any] = [
    6: 1,
    13: 4,
    18: NSExpression(format: "MGL_MATCH(class, 'motorway', 18, 'trunk', 18, 'primary', 11, 'secondary', 7, 'tertiary', 7, 0)"),
    20: NSExpression(format: "MGL_MATCH(class, 'motorway', 33, 'trunk', 33, 'primary, 18.5, 'secondary', 14, 'tertiary', 14, 0)")
]
NSExpression(format: "mgl_interpolate:withCurveType:parameters:stops:($zoomLevel, 'exponential', 1.5, %@)", stops)
```

**Comment by lorenzhahaha** [comment]
I'm new in mapbox. Can you please tell me how to do this one? From a beginner's perspective please.

**Comment by langsmith** [comment]
Hey @lorenzhahaha , I'm trying to figure it out myself haha. Implementing this is based on how much traffic you want to "animate". E.g. just the "primary" traffic lines? All of the traffic, even in the smaller streets? _Just_ the red/congested areas?

I'm thinking about doing a straightforward example of animating the dashes of a lineLayer line. It won't have anything to do with traffic though.

Related to this is the traffic plugin. See https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java#L372-L375 and https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java#L163-L167 .  That's why I made https://github.com/mapbox/mapbox-plugins-android/issues/484

**Comment by langsmith** [comment]
Closing because this functionality could/should be brought to the traffic plugin (first).
