### ISSUE TITLE
New logo design for Map Box

### ISSUE THREAD

**Issue by sametceylan** [mapbox/mapbox-android-demo#692]
Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for Map Box. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

**Comment by langsmith** [comment]
Hi Samet,

Thanks for reaching out and for your interest in Mapbox. This repo is for the Mapbox demo app, so I'm going to close this ticket. If you're interested in Mapbox design, keep an eye on mapbox.com/careers for any future design opportunities! 🚀
