### ISSUE TITLE
LocationLayer plugin problem

### ISSUE THREAD

**Issue by lorenzhahaha** [mapbox/mapbox-android-demo#701]
<a href="https://ibb.co/cwCzTn"><img src="https://preview.ibb.co/k2KeTn/Screen_Shot_2018_05_05_at_4_45_37_PM.png" alt="Screen_Shot_2018_05_05_at_4_45_37_PM" border="0"></a><br>

<a href="https://ibb.co/fM0xES"><img src="https://preview.ibb.co/eoPPuS/Screen_Shot_2018_05_05_at_4_50_10_PM.png" alt="Screen_Shot_2018_05_05_at_4_50_10_PM" border="0"></a><br>

I don't know what really is the problem. What I did is just follow the instructions in <a href="https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java">here</a> but I still can't see my location. I have read the documentation on how to implement this from <a href="https://www.mapbox.com/android-docs/plugins/overview/location-layer/">this link</a>. I thought that it was caused by the mixing of libraries but when I started a new project (which I have made for about 10+ times), I still face same warning. I am facing this problem for almost 3 days. I am so sad why do I can't get my location which is very simple in google map. What I just want is to implement mapbox which in the first phase is to get user's location. Please help me. 

**AS version: 3.1.2
Current emulator android version: API 27
Support version: 27.1.1**

Same problem even with Emulator or Physical device. I can't get user's location and also the blue gps icon.

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig { 
        applicationId "com.a1ks.toandfro" 
        minSdkVersion 19 
        targetSdkVersion 27 
        versionCode 1 
        versionName "1.0" 
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner" 
    }
    buildTypes { 
        release { 
            minifyEnabled true 
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        } 
    } 
    buildToolsVersion '27.0.3' 
    compileOptions { 
        sourceCompatibility JavaVersion.VERSION_1_8 
        targetCompatibility JavaVersion.VERSION_1_8 
    } 
}

dependencies {
implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.android.support:appcompat-v7:$support_version"
    implementation "com.android.support:design:$support_version"
    implementation "com.android.support:support-v4:$support_version"
    implementation "com.android.support:recyclerview-v7:$support_version"
    implementation "com.android.support:cardview-v7:$support_version"
    implementation "com.android.support:support-vector-drawable:$support_version"

    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.0.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-offline:0.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.0'
}

**Comment by polekar-ankit** [comment]
I am also facing the same issue ...please help me to resolve this .

**Comment by langsmith** [comment]
Hey @lorenzhahaha and @polekar-ankit . Thanks for using Mapbox. 

It might be the way you're implementing the plugin. Hard to tell without seeing your code. @cammace has made many great improvements to [the Location Layer Plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer).  Use the plugin's example in the demo app as a reference: https://github.com/mapbox/mapbox-android-demo/blob/1f08f1c3168f55b2d74c4c12e12ac5f96a093d5e/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java  . The example has been updated to reflect his changes.

If you're _still_ having issues, then please create a ticket at https://github.com/mapbox/mapbox-plugins-android/issues/new
