### ISSUE TITLE
language for Cambodia

### ISSUE THREAD

**Issue by SunryTeang** [mapbox/mapbox-android-demo#708]

**Comment by langsmith** [comment]
Hi @SunryTeang , what type of language support would you like?

[Here's information about language requests for the Mapbox Navigation and Maps SDKs for Android](https://github.com/mapbox/mapbox-navigation-android/blob/ee49c0905d9beb134cdf60db745e7bbd250d3e1f/CONTRIBUTING.md#adding-or-updating-a-localization)

**Comment by langsmith** [comment]
Closing because no response. We can re-open if this conversation gets going again.
