### ISSUE TITLE
Cache example images

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#71]
Images should be cached locally.

**Comment by tobrun** [comment]
To give a bit more context, I noticed images needed to load after just restarting the application. 
I need to add that Jake Wharton advices to not use a cache and rely on HttpClient caching instead. First step should be to enable the debug mode on Picasso and validate if the image comes from the cache with `setIndicatorsEnabled(true)`. More information [here](http://stackoverflow.com/a/23281195/1281750).

**Comment by langsmith** [comment]
@tobrun & @cammace, I created a new branch to look into this issue and added the following to the Main Activity's onCreate():

```java
Picasso.with(this).setIndicatorsEnabled(true);
Picasso.with(this).setLoggingEnabled(true);
```

A few of the cardview images have the blue corners in their upper left hand corners, but I'll continue looking into this. Not really sure what Wharton means when says "If you never see a blue indicator, it's likely that your remote images do not include proper cache headers to enable caching to disk." Would love to hear any suggestions on potential solutions to look into for this. No worries if not. @cammace , perhaps you and I can discuss this on Monday...

![screenshot_20170406-180443](https://cloud.githubusercontent.com/assets/4394910/24813219/0cd4300e-1b82-11e7-9104-5b63253607ee.png)
![screenshot_20170406-180412 1](https://cloud.githubusercontent.com/assets/4394910/24813218/0cd3b584-1b82-11e7-8454-6d1f21caf851.png)

**Comment by langsmith** [comment]
I should add that I first play around with Picasso a bit and added that `setIndicatorsEnabled(true)` line. It displayed on some of the images upper left corner (see screenshots below). I then read more about Picasso's caching and some of Jake Wharton's comments around the web. Sounded like Picasso doesn't make caching particularly easy. 

All of that said:


<img width="300" alt="screen shot 2017-04-08 at 6 24 25 am" src="https://cloud.githubusercontent.com/assets/4394910/24829327/0ef9bdf2-1c24-11e7-9c59-c507df3f81ca.png">




<img width="427" alt="screen shot 2017-04-08 at 5 56 21 am" src="https://cloud.githubusercontent.com/assets/4394910/24829082/1e168954-1c20-11e7-9c2e-0adec47aabf9.png">
<img width="415" alt="screen shot 2017-04-08 at 5 56 15 am" src="https://cloud.githubusercontent.com/assets/4394910/24829083/1e186a3a-1c20-11e7-8098-e7084f1cc93e.png">

**Comment by zugaldia** [comment]
> @tobrun & @cammace, I don't know if you've ever experimented with Facebook's Fresco, but it's pretty damn sweet.

My understanding is that Facebook's Fresco is great when you are at Facebook's scale and need to handle a _large_ number of pictures. At that point, Fresco's optimizations start to pay off. Otherwise, I don't see any feature we need that Picasso doesn't already offer?
