### ISSUE TITLE
how to dragger the marker

### ISSUE THREAD

**Issue by q3226257** [mapbox/mapbox-android-demo#711]
the google map can set marker dragger is true,how to get this in mapbox?can you tell me how to do ?

**Comment by langsmith** [comment]
Hi @q3226257 ,

We're aware of this potential product feature and [already have a ticket open in the Mapbox GL Native repo regarding draggable markers](https://github.com/mapbox/mapbox-gl-native/issues/2450).

It's not exactly dragging a marker, but you should know about [this demo app example](https://github.com/mapbox/mapbox-android-demo/blob/2f90c88df82fccc8bb6b1488465649d2ab479329/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/annotations/AnimatedMarkerActivity.java), which moves a marker to a new map click location.
