### ISSUE TITLE
Mapbox waypoint or location arrival event is not found in android

### ISSUE THREAD

**Issue by kinDSa** [mapbox/mapbox-android-demo#716]
I am using mapbox library for turn by turn navigation. In my application I need to perform some action when user reach to particular waypoints(stop-point). In IOS, there is **didArriveAt** method which call when reach to particular waypoint. I have search a lot but not found method like that in android. I found **onArrival** method but It's not call at waypoint arrive. Is there any way to know to reach that waypoint?

**Comment by danesfeder** [comment]
Hey @kinDSa, unfortunately we don't have a listener for triggered arrival events in the Navigation SDK at the moment https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#listening-to-the-navigationview.

I've opened a feature ticket in the navigation repo to track this --> https://github.com/mapbox/mapbox-navigation-android/issues/955

In the meantime, you can use `RouteUtils#isArrivalEvent(RouteProgress)` in a `ProgressChangeListener` added to your `NavigationView` that can check every progress update and determine if a user is arriving.  

Thanks for checking out the SDK!
