### ISSUE TITLE
Usage of BaseMarkerOptions

### ISSUE THREAD

**Issue by abhinav-adtechs** [mapbox/mapbox-android-demo#72]
Please show the usage of BaseMarkerOptions which is used in the method addMarkers and addMarker of MapboxMap class.

I wish to fetch a relevant list of markers and directly draw it on the map.

**Comment by cammace** [comment]
Hey @abhinav-adtechs thanks for your interest in the Mapbox Android SDK and using the demo app. BaseMarkerOptions is just an abstract class `MarkerOptions()` uses. You can follow [this example to draw a marker](https://www.mapbox.com/android-sdk/examples/marker/) using `MarkerOptions`, if you have further questions please [contact us on our website](https://www.mapbox.com/contact/). Thanks again!
