### ISSUE TITLE
mapbox maproute isNaN error

### ISSUE THREAD

**Issue by kobe8ouchao** [mapbox/mapbox-android-demo#721]

**Comment by langsmith** [comment]
Hey @kobe8ouchao , thanks for using Mapbox! 

Does this cause an actual crash of your app? Or is just an error in your console while the app is working fine?

Any `getCameraForLatLngBound()` related code that you can share?

**Comment by kobe8ouchao** [comment]
private void animateCameraBbox(LatLngBounds bounds, int animationTime, int[] padding) {
        CameraPosition position = mapboxMap.getCameraForLatLngBounds(bounds, padding);
        mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(position), animationTime);
    }

Above is my code, the function is move the camera to bounds, but it will crash by call this method, the exception is NaN

**Comment by langsmith** [comment]
In this case, `NaN` stands for "**N**ot **A** **N**umber", which seems that something's wrong with your coordinates for some reason 🤔  https://github.com/mapbox/mapbox-gl-native/search?q=latitude+must+not+be+NaN&unscoped_q=latitude+must+not+be+NaN

I suspect that you're passing incorrect values for the `LatLngBounds bounds` parameter of `animateCameraBbox()`. That's what I'd look into.

Also make sure that your `mapboxMap` is initialized before you run `animateCameraBbox()`? Running`animateCameraBbox()` within `onMapReady()` is one way to do this.

https://www.mapbox.com/contact/support/#products/andrxoid is a good place for continued help with this issue.
