### ISSUE TITLE
Fix local JSON with vector tile

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#725]
The example of local JSON data with vector tiles isn't working

![device-2018-05-23-170728](https://user-images.githubusercontent.com/4394910/40457534-d2e84bf0-5eab-11e8-819a-ffcd3a3311ad.png)

**Comment by garyharris686** [comment]
[file.txt](https://github.com/mapbox/mapbox-android-demo/files/2070325/file.txt)

**Comment by langsmith** [comment]
@garyharris686 ?
