### ISSUE TITLE
MapBox crash when

### ISSUE THREAD

**Issue by kobe8ouchao** [mapbox/mapbox-android-demo#731]
05-28 18:11:01.616 12050-12050/? A/DEBUG: Build fingerprint: 'samsung/nobleltezh/nobleltehk:7.0/NRD90M/N9200ZHU3DRD1:user/release-keys'
    Revision: '9'
    ABI: 'arm'
    pid: 11410, tid: 11410, name: obot.mirrorlink  >>> im.autobot.mirrorlink <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
05-28 18:11:01.617 12050-12050/? A/DEBUG:     r0 00000000  r1 f414b6ca  r2 00430000  r3 e88309dc
        r4 00000000  r5 e89252a0  r6 ffa702c0  r7 ffa70170
        r8 ffa70100  r9 e8905400  sl ffa701d0  fp e8905400
        ip e89252a0  sp ffa700a8  lr e84d69b5  pc c3ffe4b8  cpsr 60070030
		05-28 18:11:02.082 12050-12050/? A/DEBUG: backtrace:
        #00 pc 000964b8  /data/app/im.autobot.mirrorlink-1/lib/arm/libmapbox-gl.so
        #01 pc 00097c25  /data/app/im.autobot.mirrorlink-1/lib/arm/libmapbox-gl.so
        #02 pc 00097c67  /data/app/im.autobot.mirrorlink-1/lib/arm/libmapbox-gl.so
        #03 pc 000adc99  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
        #04 pc 000a92c1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
        #05 pc 00407949  /system/lib/libart.so (art_quick_invoke_stub+232)
        #06 pc 000b05b5  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+140)
        #07 pc 001eda4b  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+198)
        #08 pc 001e7feb  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+478)
        #09 pc 00400213  /system/lib/libart.so (MterpInvokeDirect+270)
        #10 pc 0009c214  /system/lib/libart.so (ExecuteMterpImpl+14484)
        #11 pc 001cbe07  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
        #12 pc 001d08b7  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
        #13 pc 001e7fcf  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+450)
        #14 pc 003ff317  /system/lib/libart.so (MterpInvokeVirtual+430)
        #15 pc 0009c114  /system/lib/libart.so (ExecuteMterpImpl+14228)
        #16 pc 001cbe07  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
        #17 pc 001d08b7  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
        #18 pc 001e7fcf  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+450)
        #19 pc 00400213  /system/lib/libart.so (MterpInvokeDirect+270)
        #20 pc 0009c214  /system/lib/libart.so (ExecuteMterpImpl+14484)
05-28 18:11:02.083 12050-12050/? A/DEBUG:     #21 pc 001cbe07  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
        #22 pc 001d08b7  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
        #23 pc 001e7fcf  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+450)
        #24 pc 00400213  /system/lib/libart.so (MterpInvokeDirect+270)
        #25 pc 0009c214  /system/lib/libart.so (ExecuteMterpImpl+14484)
        #26 pc 001cbe07  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
        #27 pc 001d08b7  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
        #28 pc 001e7fcf  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+450)
        #29 pc 00400013  /system/lib/libart.so (MterpInvokeInterface+842)
        #30 pc 0009c314  /system/lib/libart.so (ExecuteMterpImpl+14740)
        #31 pc 001cbe07  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
        #32 pc 001d0821  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+92)
        #33 pc 003f6dcd  /system/lib/libart.so (artQuickToInterpreterBridge+716)
        #34 pc 000add13  /system/lib/libart.so (art_quick_to_interpreter_bridge+34)
        #35 pc 01f1d2bb  /system/framework/arm/boot-framework.oat (offset 0x1edc000) (android.animation.ValueAnimator.animateValue+206)
        #36 pc 01f1e36f  /system/framework/arm/boot-framework.oat (offset 0x1edc000) (android.animation.ValueAnimator.setCurrentFraction+218)
        #37 pc 01f1e40f  /system/framework/arm/boot-framework.oat (offset 0x1edc000) (android.animation.ValueAnimator.setCurrentPlayTime+106)
        #38 pc 01f1cdcf  /system/framework/arm/boot-framework.oat (offset 0x1edc000) (android.animation.ValueAnimator.start+594)
        #39 pc 01f1eb61  /system/framework/arm/boot-framework.oat (offset 0x1edc000) (android.animation.ValueAnimator.start+44)
        #40 pc 01f13cad  /system/framework/arm/boot-framework.oat (offset 0x1edc000) (android.animation.AnimatorSet.start+80)
        #41 pc 01f1122d  /system/framework/arm/boot-framework.oat (offset 0x1edc000) (android.animation.AnimatorSet.onChildAnimatorEnded+240)
        #42 pc 01f13b19  /system/framework/arm/boot-framework.oat (offset 0x1edc000) (android.animation.AnimatorSet.start+396)
        #43 pc 000a92c1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
        #44 pc 00407949  /system/lib/libart.so (art_quick_invoke_stub+232)
        #45 pc 000b05b5  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+140)
        #46 pc 001eda4b  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+198)
        #47 pc 001e7feb  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+478)
        #48 pc 003ff317  /system/lib/libart.so (MterpInvokeVirtual+430)
        #49 pc 0009c114  /system/lib/libart.so (ExecuteMterpImpl+14228)
        #50 pc 001cbe07  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
        #51 pc 001d08b7  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
        #52 pc 001e7fcf  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+450)
        #53 pc 00400213  /system/lib/libart.so (MterpInvokeDirect+270)
        #54 pc 0009c214  /system/lib/libart.so (ExecuteMterpImpl+14484)
        #55 pc 001cbe07  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
        #56 pc 001d08b7  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
        #57 pc 001e7fcf  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+450)
        #58 pc 003ff317  /system/lib/libart.so (MterpInvokeVirtual+430)
        #59 pc 0009c114  /system/lib/libart.so (ExecuteMterpImpl+14228)
        #60 pc 001cbe07  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
        #61 pc 001d08b7  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
05-28 18:11:02.084 12050-12050/? A/DEBUG:     #62 pc 001e7fcf  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+450)
        #63 pc 00400213  /system/lib/libart.so (MterpInvokeDirect+270)

**Comment by kobe8ouchao** [comment]
it crash when init mapview, how is going?

**Comment by langsmith** [comment]
Hi @kobe8ouchao , thanks for using Mapbox. Going to close this because it's not related to the Android demo app.

Make sure you're using [a valid Mapbox access token](https://www.mapbox.com/help/how-access-tokens-work/). Lots of initialization problems can be related to that. 

https://www.mapbox.com/contact/support/#products/andrxoid is a good place for continued help with this issue
