### ISSUE TITLE
How to give different colours to Polygon features present in single fill layer.

### ISSUE THREAD

**Issue by viveksaruk** [mapbox/mapbox-android-demo#733]
Below is my code where I am creating polygon feature and adding it in a single layer.

public void drawPlots() {

		final List<PlotCrop> plotCropsList = PlotUtils.getAllPlotCropsList();

		if (plotCropsList != null) {

			for (PlotCrop plotCrop : plotCropsList) {

				final List<List<Position>> plotPolygonPositions = new ArrayList<>();
				List<List<Double>> plotCropCoordinatesList = PlotUtils.getPlotCropCoordinatesList(plotCrop);

				if (plotCropCoordinatesList != null) {
					List<Position> plotCoordinatePosition = getPositionByCoordinates(plotCropCoordinatesList);
					plotPolygonPositions.add(plotCoordinatePosition);
					createPlotFeature(plotPolygonPositions, plotCrop.getProperties().getPlotSlug(), ContextCompat.getColor(mActivity, R.color.plot_polygon), null, plotCrop);
				}
			}

			addSourceToMapbox(Constants.MapBoxStrings.PLOTS_SOURCE, mPlotFeatureArray);

			FillLayer fillLayer = new FillLayer(Constants.MapBoxStrings.PLOTS_LAYER, Constants.MapBoxStrings.PLOTS_SOURCE);
			fillLayer.setProperties(PropertyFactory.fillColor(ContextCompat.getColor(mActivity, R.color.plot_polygon)));
			mMapboxMap.addLayerAbove(fillLayer, Constants.MapBoxStrings.FIELDS_LAYER);
			drawFarms();
		}
	}

	public void createPlotFeature(final List<List<Position>> polygonPositions, final String slug, final int color, final Field field, final PlotCrop plotCrop) {

		Feature feature = Feature.fromGeometry(com.mapbox.services.commons.geojson.Polygon.fromCoordinates(polygonPositions));
		feature.setId(slug);
		if (plotCrop != null && feature != null) {
			mMapboxIdObjectMap.put(feature.getId(), plotCrop);
			mPlotFeatureArray.add(feature);
		}
	}

 Above I am giving color to fill layer, but I want to give specific color to plot feature defined by my plotCrop object.

**Comment by langsmith** [comment]
Hi @viveksaruk , thanks for using Mapbox! I'm not exactly sure what you're trying to do. However:

- Polygons can be given fill color. See https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/annotations/DrawPolygonActivity.java#L46-L64

- Another option is to add the color as a String property for a single `Feature` with `.addStringProperty()` 👇 
<img width="564" alt="screen shot 2018-05-31 at 9 08 03 am" src="https://user-images.githubusercontent.com/4394910/40793835-5b8059ec-64b2-11e8-8a94-e7f96372873d.png">

**Comment by viveksaruk** [comment]
Hi @langsmith, Thank you for the quick reply. I would like to explain what I am trying to do. 
In above example, first of all, I am
1) Creating polygon feature and adding it in an arraylist.
2) Adding this arraylist as a source to mapbox. 
3) Creating layer for this source of features by giving colour to layer directly.

But now I want to give the different colours to these Polygon sources.
Ex. Say I am adding 20 polygon features to map in single fill layer. But instead of giving colour to fill layer, out of 20 I want to give 5 polygons green colour, 5 orange, 5 blue and 5 yellow colour. How can I do it?

**Comment by langsmith** [comment]
@viveksaruk

As a more general note, I'd recommend that you use `Point` rather than `Position` in your project. `Point` replaced `Position` a while ago.

> I want to give 5 polygons green colour, 5 orange, 5 blue and 5 yellow colour. How can I do it?

For this, data-driven styling is great for what you're trying to achieve. Assign a color value to each Polygon GeoJSON feature. Add the color value as a `String` with `addStringProperty`. This way you can use the `match`, `toColor`, & `color` Expressions and data-driven styling to automatically set the polygons' colors.

**Comment by langsmith** [comment]
> Add the color value as a String with addStringProperty

Don't forget that you can also then use `getStringProperty()` if you're parsing through your lists or something.

**Comment by viveksaruk** [comment]
Hi @langsmith 

Yes, I am using Point instead of Position by updating my SDK to 6.0.0 from 5.5.0 and below code is working for me to change plot colour. Below is the code for updating SDK to 6.0.0 : 


	addSourceToMapbox(Constants.MapBoxStrings.PLOTS_SOURCE, mPlotFeatureArray);

			FillLayer fillLayer = new FillLayer(Constants.MapBoxStrings.PLOTS_LAYER, Constants.MapBoxStrings.PLOTS_SOURCE);

			int defaultColor = ContextCompat.getColor(mActivity, R.color.plot_polygon);


			Expression.Stop[] stops = new Expression.Stop[stopsList.size()];
			stopsList.toArray(stops);
			fillLayer.setProperties(
					fillColor(
							match(
									Expression.toString(get("plotSlug")),
									color(defaultColor),
									stops
							)
					)
			);

	public void createPlotFeature(final List<Point> polygonPoints, final String slug, final int color, final Field field, final PlotCrop plotCrop) {

String plotColour = plotCrop.getProperties().getColourCode();

		List<List<Point>> polygonPointsList = new ArrayList<>();
		polygonPointsList.add(polygonPoints);
		Feature feature = Feature.fromGeometry(Polygon.fromLngLats(polygonPointsList));
		feature.addStringProperty("plotSlug", slug);
				if (plotColour.startsWith(Constants.MapBoxStrings.PLOT_COLOUR_STARTS_WITH)) {
			stopList.add(Stop.stop(slug, fillColor(plotColour)));
		} else {
			stopList.add(Stop.stop(slug, fillColor(ContextCompat.getColor(mActivity, R.color.plot_polygon))));
		}
}


and below is the code for SDK 5.5.0  in which I am using categorial stop and sending it array of 'stop ' : 


	addSourceToMapbox(Constants.MapBoxStrings.PLOTS_SOURCE, mPlotFeatureArray);

			Stop[] stops = new Stop[stopList.size()];
			stopList.toArray(stops);

			FillLayer fillLayer = new FillLayer(Constants.MapBoxStrings.PLOTS_LAYER, Constants.MapBoxStrings.PLOTS_SOURCE);

			fillLayer.setProperties(
					fillColor(
							Function.<Object, String>property(Constants.MapBoxStrings.PLOT_SLUG, Stops.<Object, String>categorical(stops))
					));


public void createPlotFeature(final List<List<Position>> polygonPositions, final String slug, final int color, final Field field, final PlotCrop plotCrop) {

		String plotColour = plotCrop.getProperties().getColourCode();

		Feature feature = Feature.fromGeometry(com.mapbox.services.commons.geojson.Polygon.fromCoordinates(polygonPositions));
		feature.setId(slug);
		feature.addStringProperty(Constants.MapBoxStrings.PLOT_SLUG, slug);

		if (plotColour.startsWith(Constants.MapBoxStrings.PLOT_COLOUR_STARTS_WITH)) {
			stopList.add(Stop.stop(slug, fillColor(plotColour)));
		} else {
			stopList.add(Stop.stop(slug, fillColor(ContextCompat.getColor(mActivity, R.color.plot_polygon))));
		}
}

But by updating SDK to 6.0.0 I am facing issue with on map click for SymbolLayer. It is showing Inconsistency for the click on SymbolLayer. While fillLayer is working properly.

FYI I am using onMapClick, getting point on click and querying that point using queryRenderedFeatures() by sending it 'point' and 'layer' (in which I want to query clicked point) as an argument to match. Which returns features on which that point is present.

But it is showing Inconsistency for markers click on my map which I have added in SymbolLayer.

**Comment by langsmith** [comment]
This ticket isn't an actual issue with this demo app, so I'm going to close this ticket. If you'd like to continue a conversation about your specific questions, please use the form at https://www.mapbox.com/contact/support/#products/android
