### ISSUE TITLE
Current location icon color change blue to grey

### ISSUE THREAD

**Issue by kinDSa** [mapbox/mapbox-android-demo#735]
I am using LocationLayerPlugin for showing user current location and use default current location style.

 ```
LocationLayerPlugin locationLayer = new LocationLayerPlugin(mapView, mapboxMap, locationEngine);
locationLayer.setRenderMode(RenderMode.COMPASS);
```
When map load current location icon color is blue then after few minute is convert to gray color. What to do for remain icon color to blue.

I have attached screenshot.
![grey_current_location_icon](https://user-images.githubusercontent.com/25680329/40917899-6de23b1e-6822-11e8-94a2-34857460ef8a.png)

**Comment by LukasPaczos** [comment]
The location icon turning grey indicates that you did not receive any location updates in some time, a.k.a. the stale state. The default value is 30 seconds. You can increase/decrease that value or disable this functionality altogether with `LocationLayerOptions`.
