### ISSUE TITLE
SymbolLayerMapillaryActivity issues

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-android-demo#737]
After the migration to expressions I noticed a couple of issue with [SymbolLayerMapillaryActivity](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerMapillaryActivity.java):
- doesn't display loading circle due to [this lines](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerMapillaryActivity.java#L260-L261)
- doesn't make clustering circles invisible when we zoom close enough to actually see the picture
- loading process is improperly interruted and persist when changing the POI during the loading animation
- callout layer "grows" a bit after being initially clicked

**Comment by langsmith** [comment]
Thanks @LukasPaczos
