### ISSUE TITLE
Centre programmatically

### ISSUE THREAD

**Issue by HoussemHfaidh** [mapbox/mapbox-android-demo#76]
How to set camera and view centre with onLocationChange ,you can help me ???

**Comment by cammace** [comment]
Hey @HoussemHfaidh,

It sounds like you are trying to track user location? If this is the case you can use [this example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java) in the testapp to work off of. To enable tracking you use this line:

    mapboxMap.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);

For future questions, i'd like to recommend contacting us through [support](https://www.mapbox.com/contact/).
