### ISSUE TITLE
Customizing User Location

### ISSUE THREAD

**Issue by subhechhu** [mapbox/mapbox-android-demo#763]
Annotation does have a custom marker icon but adding radius isn't being possible to the user location. Is there any way to add the radius around the custom marker icon like [here](http://www.mapbox.com.s3-website-us-east-1.amazonaws.com/android-sdk/examples/customize-user-location/)?
Can it be customized [as shown here](https://www.mapbox.com/ios-sdk/images/examples/switch-between-user-tracking-modes.mp4)?

![customize-user-location](https://user-images.githubusercontent.com/13517085/41953132-89acbfbe-79f1-11e8-88ca-f801b7146afb.png)

**Comment by langsmith** [comment]
Hey @subhechhu , thank you so much for using Mapbox. This isn't an actual issue with this demo app, so I'm going to close this ticket. 

[The Mapbox Location Layer Plugin](https://www.mapbox.com/android-docs/plugins/overview/location-layer/) doesn't currently provide a way to adjust the radius. You could copy/paste the plugin's code into your project and "roll your own" plugin by adjusting the radius behavior in the custom code.

If you'd like to continue a conversation about your specific questions, please use the form at https://www.mapbox.com/contact/support/#products/android
