### ISSUE TITLE
How to set iconOffset  with Source Properties

### ISSUE THREAD

**Issue by zhuxixiang** [mapbox/mapbox-android-demo#764]
I have added properties named "xoffset" and "yoffset"  in `GeoJsonSource` and added the source to my mapbox. 
now, I want to construct a `iconOffset` property whose paramters should be `Float[]` or `Expression`. How could I build the paramters  using the "xoffset","yoffset" from my source? How to construct  an Expression 
using `Expression.toNumber(Expression.get("xoffset"))` and `Expression.toNumber(Expression.get("yoffset"))`?

Env: mapbox 6.1.3

CODE:
```
mMarkerProperties = new PropertyValue[]{
                PropertyFactory.iconImage("{icon}"),
                PropertyFactory.iconAnchor(ICON_ANCHOR_BOTTOM),
                PropertyFactory.iconAllowOverlap(true),
                PropertyFactory.iconOffset(new Expression(
                        "array",
                        Expression.toNumber(Expression.get("xoffset")), Expression.toNumber(Expression.get("yoffset"))
                ))
               };
```

**Comment by langsmith** [comment]
This ticket isn't an actual issue with this demo app, so I'm going to close this ticket. If you'd like to continue a conversation about your specific questions, please use the form at https://www.mapbox.com/contact/support/#products/android
