### ISSUE TITLE
Can't retrieve user's current location

### ISSUE THREAD

**Issue by w33haa2** [mapbox/mapbox-android-demo#779]
![37112090_1801928713206261_548236860049063936_n](https://user-images.githubusercontent.com/33534250/42734387-7ec4ca14-8875-11e8-985f-67c0c230a26c.png)

The app cant retrieve my location, it just redirects me to a random place.

**Comment by riastrad** [comment]
Noting here that I've confirmed this behavior within the app as well. Both in the version that's available in the Play Store and a version I built from source.

cc: @langsmith

**Comment by langsmith** [comment]
Hi @riastrad  and @w33haa2 . https://github.com/mapbox/mapbox-plugins-android/issues/606 happened recently and a new version of the demo app went out with it. Are you still seeing location layer plugin issues on your devices?

**Comment by riastrad** [comment]
Hey @langsmith thanks for flagging. Unfortunately I'm still seeing the same behavior described above after updating the demo app to v6.3.0-4. 

For reference this is on a Pixel XL that's running Android 8.1.0.

**Comment by qlerebours** [comment]
Hi ! I also noticed this issue about retrieving user's location. I tried on 4 different devices:
 - Huawai Android 7.0: Failure
 - Xiaomi MI5, Android 6.0: Failure
 - Motorola, Android 7.1.1: Success
 - Sony Xperia, Android 8.0: Success

**Comment by langsmith** [comment]
cc @danesfeder @Guardiola31337 @LukasPaczos as fyi that location plugin is being discussed here too

**Comment by Guardiola31337** [comment]
We're tracking that issue in mapbox/mapbox-events-android#187 - which seems a device specific issue (based on your findings) when using the Android APIs (`AndroidLocationEngine`) as the demo app does.

Could you confirm that if you're not stale this is not a problem in your failing devices?

When I say stale, I mean moving and getting more than one location update (e.g. going on a test drive). That'd help us on finding the root cause of mapbox/mapbox-events-android#187 (from our tests is only a problem for the first location fix).

Thanks!

cc @w33haa2 @riastrad @qlerebours @electrostat

**Comment by riastrad** [comment]
@Guardiola31337 I did some field testing and the user location eventually showed up in the demo app, but it took a good 30 minutes of walking around and taking the metro before it did.

This was on a Samsung Galaxy Note8 running Android 8.0.

**Comment by langsmith** [comment]
> it took a good 30 minutes of walking around and taking the metro before it did

I've experienced this too on my OnePlus 5

**Comment by qlerebours** [comment]
I had to wait too before getting my location on the map

**Comment by Guardiola31337** [comment]
@qlerebours 
> I had to wait too before getting my location on the map

How long? Did that happen with all the devices mentioned in https://github.com/mapbox/mapbox-android-demo/issues/779#issuecomment-411332690? Could you describe your use case in detail? Did the app go to background? Thanks!

**Comment by langsmith** [comment]
Have folks still been having problems with getting the device's location? There have been improvements to the location layer plugin. [It's also been deprecated](https://github.com/mapbox/mapbox-gl-native/pull/12786). _"The development and maintenance of the location features will happen in the Maps SDK project from now on."_

**Comment by wuxuenan** [comment]
> Have folks still been having problems with getting the device's location? There have been improvements to the location layer plugin. [It's also been deprecated](https://github.com/mapbox/mapbox-gl-native/pull/12786). _"The development and maintenance of the location features will happen in the Maps SDK project from now on."_
Can't retrieve user's current location . My Version6.6.5

**Comment by langsmith** [comment]
Just commented here @wuxuenan https://github.com/mapbox/mapbox-android-demo/issues/904#issuecomment-436441612

Lots of improvements have been made to location and the Maps SDK. Location issues have appeared to go down. Please contact [Mapbox Support](https://www.mapbox.com/contact/support/) if you have issues. Thanks for using Mapbox!
