### ISSUE TITLE
Enable an easy setting to switch all styles to a custom style in demo app

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-android-demo#80]
We want to have an easy way to test a custom style in all activities of the demo app. I'm thinking of exposing a global constant that, if set, overrides the default style set by the different activities in the app.

This wouldn't be used in the production app, only for custom builds and development purposes.

/cc: @cammace

**Comment by cammace** [comment]
This might be more fitting for the testapp, Doing this in the demo app makes each example a little longer and might cause confusion. Currently the examples are direct copy's of the ones on the website. adding a flag to each example would mean all the examples on the site would reflect that. Maybe the `clientwork` branch is more suited for something like this and will consider it next time I build examples in that branch. Closing for now
