### ISSUE TITLE
Missing feature: WATCH. What's it ?

### ISSUE THREAD

**Issue by alexd555** [mapbox/mapbox-android-demo#848]
Missing feature: WATCH. What's it ?

**Comment by langsmith** [comment]
Hey @alexd555. What do you mean? There is a wearable demo app in this repo

**Comment by alexd555** [comment]
I got this error when I try to run on sumsung galaxy s5. 
I'm looking for example of appliction where you can find people around by preferences and location around.
Can you help ?
@langsmith

**Comment by tobrun** [comment]
Next to the run button there is a drop-down where you can select the module to run, you need to switch to the phone module instead of wear

**Comment by AhmadullahSaikat** [comment]
Please check the image.

![image](https://user-images.githubusercontent.com/15679818/48675358-36a72680-eb82-11e8-9bd6-b40d3162a5fd.png)
