### ISSUE TITLE
Clustering wihtout geoJson

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-android-demo#849]
Is there any way, we can add clustering without geojson?

* I had cluster plugin with me but unable to use with new sdk release with navigation.

**Comment by langsmith** [comment]
Hi @mf-mindcrewtech , thanks for using Mapbox.

Using GeoJSON and map layers together is the best way to add data clusters. This implementation method gives you the most flexibility and power for showing data the way that you want.

https://www.mapbox.com/android-docs/maps/overview/clustering/
