### ISSUE TITLE
using the sdk 6.4.0 need java1.8

### ISSUE THREAD

**Issue by darkdddd** [mapbox/mapbox-android-demo#861]
Using the sdk 6.4.0 need java 1.8, but the java 1.8 need API level 24 or higher.
But the min api of our project  is 19, so we couldn't use the sdk. We can only use jack to support java 1.8. But google already abandon the using of the jack.So how could we using the sdk 6.4.0 with the min api under the level 24?
 jackOptions {
            enabled true
        }
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by tobrun** [comment]
You need to bump your used tooling:
Some example build.gradle files:
 - project specific [build.gradle](https://github.com/mapbox/mapbox-android-demo/blob/master/build.gradle)
 - app specific [build.gradle](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/build.gradle)
 - dependencies file [here](https://github.com/mapbox/mapbox-android-demo/blob/master/gradle/dependencies.gradle)

Bumping these should enable you to remove the jackOptions and just rely on the compileOptions section. Closing this issue as answered, thank you for reaching out!
