### ISSUE TITLE
GeoJsonSource from local file

### ISSUE THREAD

**Issue by TooLazyy** [mapbox/mapbox-android-demo#885]
Is it possible in Android to create `GeoJsonSource` from a local geojson `File` by passing a local file's url?
`File(localFilePath).toURI().toURL()` is not working. And i'm note sure pass the whole `File` as `String` is a memory efficient solution (Source file could contains more than 1000 elements).

**Comment by langsmith** [comment]
I've never done anything local File paths before 🤔  @LukasPaczos @tobrun , any idea whether this type of GeoJSON loading is possible?

**Comment by LukasPaczos** [comment]
Thanks for reaching out @TooLazyy! Unfortunately, you can't load a file straight to a Java object, you will have to parse the file into a `String` and then `FeatureCollection` and pass it to the `GeoJsonSource`'s constructor. You can see an example of that in the [`SymbolGeneratorActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java#L217-L219). The example [reads a resource](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/ResourceUtils.java#L17-L32) but it will work similarly with a `File`.

Please let us know if the solution doesn't work for you. Closing as answered.

**Comment by tobrun** [comment]
@TooLazyy could you share the exception you are hitting? the used snippet should technically work. You can load GeoJson from either local, assets or online filesource.

**Comment by palimad** [comment]
Hello I have same issue, any idea how to solve it? Our feature collection is too large to handle via strings. I get [HTTP] Unable to parse resourceUrl /data/user/0/appid/files/sections.json exception

**Comment by langsmith** [comment]
@palimad , how are you trying to load the `sections.json` file? The current way the demo app does? https://github.com/mapbox/mapbox-android-demo/search?q=LoadGeoJson+extends&unscoped_q=LoadGeoJson+extends 

Kotlin + coroutines is a good replacement for the AsyncTask way of loading the GeoJSON.
