### ISSUE TITLE
Secure Request pbf Tiles With Basic Authorization

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-android-demo#910]
I need to secure my style json. i have seen some projects that directly set json url to mapView.setStyleUrl(http://sample.style.json) but in style json there is some sources with x/y/z format that need authorization to get pbf data and it works fine.
I couldn't find any approach that set authorization for tiles.
Is there any way to set basic authorization for pbf tiles ?

Thanks in advanced.

**Comment by langsmith** [comment]
Hey @AliKhoshraftar , thanks for using Mapbox. Issues in this repo are for this demo app. Your question is best reserved for https://www.mapbox.com/contact/support, so please contact the Mapbox team via https://www.mapbox.com/contact/support.
