### ISSUE TITLE
implement buttons into infowindows mapbox - android

### ISSUE THREAD

**Issue by quimico99** [mapbox/mapbox-android-demo#916]
I'm trying to implement an interactive infowindows in my map (android), with button or edittext, but I don't have a reference of how to do it, I've only seen that they simulate an ineraction but it's not the foundation to have buttons inside and to implement their actions.

**Comment by langsmith** [comment]
Hey @quimico99 , thanks for looking into Mapbox. This isn't an issue with the actual demo app, but rather, a question that's best reserved for https://www.mapbox.com/contact/support/#products/android . Please contact the Mapbox team via that link and the Support team will help you get squared away.
