### ISSUE TITLE
Offline geocoding

### ISSUE THREAD

**Issue by Merseyside** [mapbox/mapbox-android-demo#950]
Hi! I got a question, so how can I get an address while my phone isn't online? Can I get it from preloaded tiles?

**Comment by jealalbar** [comment]
yes

**Comment by Merseyside** [comment]
How can I do this?

**Comment by langsmith** [comment]
Hey @Merseyside , thanks for using Mapbox! Sorry for the delayed response. Right now, there's no way to do offline geocoding on Android devices. 

There are some ways to do cached geocoding responses for enterprise-level customers:

https://docs.mapbox.com/api/search/#mapboxplaces-permanent

https://docs.mapbox.com/api/search/#geocoding-restrictions-and-limits

**Comment by jealalbar** [comment]
Hey,
I found this amazing app on the google play store and I think you may like
it.

CPU Information - Free
View your device info in 3D for Android.
https://play.google.com/store/apps/details?id=com.aqamob.cpuinformation


Brought to you by:
http://www.ParallelAxiom.com

jl.joker
