### ISSUE TITLE
External sources referenced without safe connection

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-android-demo#955]
Android API level 28 and higher doesn't accept cleartext communication and fails to load resources in below activities:
 - `StyleCirclesCategoricallyActivity`
 - `ChoroplethZoomChangeActivity`
 - `SpaceStationLocationActivity`

For example:
```
Failed to load source ethnicity-source: CLEARTEXT communication to api.mapbox.com not permitted by network security policy
```

**Comment by langsmith** [comment]
- http://www.douevencode.com/articles/2018-07/cleartext-communication-not-permitted/
- https://stackoverflow.com/a/53349252/6358488
- https://stackoverflow.com/a/52968421/6358488

These look to be a good resources for solving this.
