### ISSUE TITLE
Add CameraMode Options Example

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-android-demo#969]
There are 7 `CameraModes` and 3 `RenderModes` available via the `LocationComponent` ([source](https://docs.mapbox.com/android/maps/overview/location-component/#cameramode)), but currently there aren't any examples that allow you to cycle through all of them. Similar to the iOS [Example](https://github.com/mapbox/ios-sdk-examples/blob/286c8d321bfc47c30f788522872810ef278cffdb/Examples/ObjectiveC/UserLocationAnnotationExample.m)[(s)](https://github.com/mapbox/ios-sdk-examples/blob/ad656dd6015e03d29feb26225397d423cd87b8c6/Examples/Swift/UserTrackingModesExample.swift), this would be a nice thing to include in the Android Demo app to help quickly visualize the differences between all the options.

I'd like to volunteer to add this to the app.

**Comment by langsmith** [comment]
Thanks @riastrad 

>I'd like to volunteer to add this to the app.

Sure, take it away. https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java could be a good reference as you build it out.
