### ISSUE TITLE
Trying to build the demo and am getting "ERROR: Failed to resolve: com.github.Cutta:GifView:1.1"

### ISSUE THREAD

**Issue by Yermo** [mapbox/mapbox-android-demo#977]
I cloned the repository and opened the project in Android Studio 3.3.1 under Ubuntu 18.04.1 LTS.

I am getting an error:

> mapbox-android-demo: ERROR: Failed to resolve: com.github.Cutta:GifView:1.1

Googling around for a few hours has produced no results.

**Comment by tobrun** [comment]
@Yermo sad to hear that you aren't able to run the mapbox-android-demo locally. The referenced dependency of GifView is https://github.com/Cutta/GifView.  Not sure why you aren't able to resolve this dependency? Would you be able to use Android Studio `invalidate caches / restart` option?

**Comment by Yermo** [comment]
I clicked on File -> Invalidate Caches/Restart

Android Studio closed and re-opened. 

The same error appears. 

> Signing not ready. Did you specify a signingConfig for the variation ChinaRelease?
Signing not ready. Did you specify a signingConfig for the variation GlobalRelease?

CONFIGURE SUCCESSFUL in 9s
ERROR: Failed to resolve: com.github.Cutta:GifView:1.1
Show in Project Structure dialog
Affected Modules: MapboxAndroidDemo

**Comment by langsmith** [comment]
Yes @Yermo , sorry that you're having issues. Very strange that the one library is causing you issues. 

The `Signing not ready.` warnings shouldn't prevent you from locally installing the app on your device either.

The `Cutta:GifView` library is just for a UI flourish in the app, so you can always just remove the library declaration from the `MapboxAndroidDemo` gradle file `implementation dependenciesList.cuttaGifView` and remove `com.cunoraz.gifview.library.GifView` from the  `layout/activity_loading.xml` and `layout/activity_landing.xml` XML files.

**Comment by Yermo** [comment]
Thank you for the replies. I sincerely appreciate it. My suspicion is there is something else wrong with the Android Studio installation. After removing the references as instructed above, I am getting a "sync failed" but no explanation why.

Sadly, I am not very familiar with Android Studio. 

I am working on a NativeScript app using Mapbox GL Android SDK v 7.1.2 and am having some problems understanding how to correctly use querySourceFeatures() [(response to my question here)](https://github.com/mapbox/mapbox-gl-native/issues/13972#issuecomment-466421420) so my thought was to build the demo app and see if I can query my GeoJSON source directly in Java to eliminate the possibility that my issue is related to NativeScript. 
 
I have managed to get a basic app with a marker built by following[ the tutorial. ](https://docs.mapbox.com/help/tutorials/first-steps-android-sdk/) and am now trying to integrate the [GeoJSON Line example.](https://docs.mapbox.com/android/maps/examples/draw-a-geojson-line/).

My eventual goal is to animate a line representing the track that a user is following (adding points to it as they travel).

**Comment by LukasPaczos** [comment]
@langsmith @tobrun are you able to build the demo app locally? I'm seeing the same exception as OP and navigating to https://jitpack.io/com/github/Cutta/GifView/1.1/GifView-1.1.aar actually returns
```
Build failed. See the log at jitpack.io
```
which would indicate that there's some upstream issue.

**Comment by langsmith** [comment]
So weird. Thanks for looking into it. I think at this time, I'll just go ahead and remove the library and the UI element. It's not a big deal for the GIF not to be in there on the welcome and loading screen. I'll figure out a replacement.

**Comment by langsmith** [comment]
Closing because #979 removed the Cutta GIF library and this issue shouldn't exist anymore. If it still does, please re-open and let me know 🙇
