### ISSUE TITLE
SymbolLayer labels operations example

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-android-demo#984]
It'd be great to add an example showcasing and focusing on various possible labels operations like how to use `text-field` property, anchors or `format` expression and highlighting what's collision detection and how to disable/manipulate it. This can be a follow up to https://github.com/mapbox/mapbox-gl-native/pull/13904.

**Comment by langsmith** [comment]
https://github.com/mapbox/mapbox-android-demo/pull/982 is awaiting review, and yes, lots more advanced text-related examples could be added to the app 🚀

**Comment by chloekraw** [comment]
yes please! strong +1

**Comment by langsmith** [comment]
@riastrad 's https://github.com/mapbox/mapbox-android-demo/pull/988 adds to our list of text-related examples

**Comment by langsmith** [comment]
I feel that this is resolved. We've got a good number of examples that show various ways to adjust text fields.
