### ISSUE TITLE
Multiple Label Styles with Format Expression

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-android-demo#985]
Given that https://github.com/mapbox/mapbox-gl-native/pull/12985 has landed, it's now possible to style a SymbolLayer's text field with multiple fonts, sizes, etc. It would be great to have an example in the app that showcased this (with a bit more polish than https://github.com/mapbox/mapbox-gl-native/pull/12985#issuecomment-469643033). Something as simple as [the example that was included in the gl-native test app](https://github.com/mapbox/mapbox-gl-native/blob/8a8291d8f4ce39d341f42c6d14b2aaad28cd854e/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java#L127-L136) should do just fine.

Note that this is a slightly different example than https://github.com/mapbox/mapbox-android-demo/pull/982 as it will have multiple styles within the textField. Though this would be complimentary to that, it shows off a different possibility for the expression. 

cc: @langsmith @chloekraw

**Comment by langsmith** [comment]
https://github.com/mapbox/mapbox-android-demo/issues/984 is related to this ticket  👥
