### ISSUE TITLE
Select a Building Example Clips at Tile Boundary

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-android-demo#992]
Poking around the demo app today I noticed that our "Select a building" example currently clips at the tile boundary for certain buildings:

![tile-sliced-buildings](https://user-images.githubusercontent.com/16272584/54160040-e69bea80-4424-11e9-9100-69d57607822f.gif)

It would be nice if it didn't do this. I think this would by solved by #854, but opening up a separate ticket just in case.

**Comment by tobrun** [comment]
@riastrad this is known limitation with how the data is structured. Basically the data is tiled and one building can consist out of one or more features across tiles. There isn't a relation between these features and no way to link one feature with another.

**Comment by langsmith** [comment]
Closing because there doesn't seem to be anything actionable.
