### ISSUE TITLE
Animate Marker up and down

### ISSUE THREAD

**Issue by MuhammadAasharib** [mapbox/mapbox-android-demo#993]
Hi, i am looking for the way to animate a marker on map up and down. But i am unable to find the solution. Thanks in advance

**Comment by langsmith** [comment]
Hi @MuhammadAasharib . Thanks for using Mapbox! See https://github.com/mapbox/mapbox-android-demo/pull/934 . It uses `iconTranslate` to adjust the marker's position up and down.
